/*
 *	Generated by 07/30/2015 11:30:14
 */


/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */



#import <XCTest/XCTest.h>
#import <libCmn/libCmn.h>



// All code under test must be linked into the Unit Test bundle
// Test Macros:
//      XCTAssert(expression, failure_description, ...)
//      XCTFail(failure_description, ...)
//      XCTAssertEqualObjects(object_1, object_2, failure_description, ...) uses isEqualTo:
//      XCTAssertEquals(value_1, value_2, failure_description, ...)
//      XCTAssertEqualsWithAccuracy(value_1, value_2, accuracy, failure_description, ...)
//      XCTAssertNil(expression, failure_description, ...)
//      XCTAssertNotNil(expression, failure_description, ...)
//      XCTAssertTrue(expression, failure_description, ...)
//      XCTAssertFalse(expression, failure_description, ...)
//      XCTAssertThrows(expression, failure_description, ...)
//      XCTAssertThrowsSpecific(expression, exception_class, failure_description, ...)
//      XCTAssertThrowsSpecificNamed(expression, exception_class, exception_name, failure_description, ...)
//      XCTAssertNoThrow(expression, failure_description, ...)
//      XCTAssertNoThrowSpecific(expression, exception_class, failure_description, ...)
//      XCTAssertNoThrowSpecificNamed(expression, exception_class, exception_name, failure_description, ...)


#include    "u16Matrix_internal.h"



uint16_t        valueCheckGet(
    MATRIX_BUILD    *pBuild,
    uint32_t        i,
    uint32_t        j
)
{
    uint32_t        base;
    uint32_t        index;
    uint32_t        highest = pBuild->highest;
    uint16_t        value = 0;

    base = pBuild->pBase[i-1];
    index = base + j - 1;
    if (index >= highest)
        ;
    else {
        if (pBuild->pCheck[index] == i) {
            value = pBuild->pValue[index];
        }
    }
    
    return value;
}



@interface u16MatrixTests : XCTestCase

@end

@implementation u16MatrixTests


- (void)setUp
{
    [super setUp];
    // Put setup code here. This method is called before the invocation of each
    // test method in the class.
    
    mem_Init( );
    
}


- (void)tearDown
{
    mem_Dump( );
    mem_Release( );

    // Put teardown code here. This method is called after the invocation of each
    // test method in the class.
    [super tearDown];
}




- (void)testOpenClose
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
   
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init( pObj, 4, 4 );
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }

    pObj = u16Matrix_NewSquare(4);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testSetGet01
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    ERESULT         eRc;
    ASTR_DATA       *pStr;
    uint16_t        max = 4;
    uint16_t        value = 0;
    
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init(pObj, max, max);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 4);
        XCTAssertTrue( (0 == value) );
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        eRc = u16Matrix_Set(pObj, 1, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 4);
        XCTAssertTrue( (0 == value) );

        eRc = u16Matrix_Set(pObj, 2, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 2);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 4);
        XCTAssertTrue( (0 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 3, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 3);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 3, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 3, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 3, 4);
        XCTAssertTrue( (0 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 4);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 4, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 4, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 4, 3);
        XCTAssertTrue( (0 == value) );
        
        pStr = u16Matrix_ToDebugString(pObj, 0);
        fprintf(stderr, "%s\n\n", AStr_getData(pStr));
        obj_Release(pStr);
        pStr = OBJ_NIL;
        
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testSetGet02
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    ERESULT         eRc;
    ASTR_DATA       *pStr;
    uint16_t        max = 4;
    uint16_t        value = 0;
    
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init( pObj, (2 * max), max );
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        eRc = u16Matrix_Set(pObj, 1, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 2, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 2);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 3, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 3);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 4);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 5, 1, 100);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 5, 1);
        XCTAssertTrue( (100 == value) );
        
        pStr = u16Matrix_ToDebugString(pObj, 0);
        fprintf(stderr, "%s\n\n", AStr_getData(pStr));
        obj_Release(pStr);
        pStr = OBJ_NIL;
        
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testIdentity01
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    ASTR_DATA       *pStr;
    uint16_t        value = 0;
    
    pObj = u16Matrix_NewIdentity(2);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 2);
        XCTAssertTrue( (1 == value) );
        
        pStr = u16Matrix_ToDebugString(pObj, 0);
        fprintf(stderr, "%s\n\n", AStr_getData(pStr));
        obj_Release(pStr);
        pStr = OBJ_NIL;

#ifdef XYZZY
        pStr = u16Matrix_CompressedTable(pObj, "test");
        fprintf(stderr, "%s\n\n\n", AStr_getData(pStr));
        obj_Release(pStr);
        pStr = OBJ_NIL;
#endif
        
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testMultiply01
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    U16MATRIX_DATA	*pObj2 = OBJ_NIL;
    U16MATRIX_DATA	*pResult = OBJ_NIL;
    ERESULT         eRc;
    uint16_t        value = 0;
    
    /*
     1   2    0  1    4  7
            X       =
     3   4    2  3    8  15
     */
    
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init(pObj, 2, 2);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        eRc = u16Matrix_Set(pObj, 1, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 1, 2, 2);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (2 == value) );
        
        eRc = u16Matrix_Set(pObj, 2, 1, 3);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (3 == value) );
        
        eRc = u16Matrix_Set(pObj, 2, 2, 4);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 2);
        XCTAssertTrue( (4 == value) );
        
        pObj2 = u16Matrix_Alloc();
        XCTAssertFalse( (OBJ_NIL == pObj2) );
        pObj2 = u16Matrix_Init(pObj2, 2, 2);
        XCTAssertFalse( (OBJ_NIL == pObj2) );
        if (pObj2) {
            
            value = u16Matrix_Get(pObj2, 1, 1);
            XCTAssertTrue( (0 == value) );
            eRc = u16Matrix_Set(pObj2, 1, 1, 0);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 1, 1);
            XCTAssertTrue( (0 == value) );
            
            eRc = u16Matrix_Set(pObj2, 1, 2, 1);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 1, 2);
            XCTAssertTrue( (1 == value) );
            
            eRc = u16Matrix_Set(pObj2, 2, 1, 2);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 2, 1);
            XCTAssertTrue( (2 == value) );
            
            eRc = u16Matrix_Set(pObj2, 2, 2, 3);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 2, 2);
            XCTAssertTrue( (3 == value) );
            
            pResult = u16Matrix_Multiply(pObj, pObj2);
            XCTAssertFalse( (OBJ_NIL == pResult) );
            XCTAssertTrue( (2 == u16Matrix_getM(pResult)) );
            XCTAssertTrue( (2 == u16Matrix_getN(pResult)) );
            
            if (pResult) {

                value = u16Matrix_getN(pResult);
                fprintf(stderr, "n = %d\n", value);
                XCTAssertTrue( (2 == value) );
                value = u16Matrix_getN(pResult);
                fprintf(stderr, "m = %d\n", value);
                XCTAssertTrue( (2 == value) );
                
                value = u16Matrix_Get(pResult, 1, 1);
                fprintf(stderr, "(1,1) = %d need 4\n", value);
                XCTAssertTrue( (4 == value) );
                
                value = u16Matrix_Get(pResult, 1, 2);
                fprintf(stderr, "(1,2) = %d need 7\n", value);
                XCTAssertTrue( (7 == value) );
                
                value = u16Matrix_Get(pResult, 2, 1);
                fprintf(stderr, "(2,1) = %d need 8\n", value);
                XCTAssertTrue( (8 == value) );
                
                value = u16Matrix_Get(pResult, 2, 2);
                fprintf(stderr, "(2,2) = %d need 15\n", value);
                XCTAssertTrue( (15 == value) );
                
                obj_Release(pResult);
                pResult = OBJ_NIL;
            }
            
            obj_Release(pObj2);
            pObj2 = OBJ_NIL;
        }
            
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testMultiply02
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    U16MATRIX_DATA	*pObj2 = OBJ_NIL;
    U16MATRIX_DATA	*pResult = OBJ_NIL;
    ERESULT         eRc;
    uint16_t        value = 0;
    
    /*
     0 0 1 1     12     15
     1 0 0 0  X   4  =  12
     1 1 0 1      9     22
     1 1 0 0      6     16
     */
    
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init(pObj, 4, 4);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (0 == value) );
        eRc = u16Matrix_Set(pObj, 1, 3, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 1, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 4);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 2, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 2);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 4);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 2);
        XCTAssertTrue( (1 == value) );
        
        pObj2 = u16Matrix_Alloc();
        XCTAssertFalse( (OBJ_NIL == pObj2) );
        pObj2 = u16Matrix_Init(pObj2, 4, 1);
        XCTAssertFalse( (OBJ_NIL == pObj2) );
        if (pObj2) {
            
            value = u16Matrix_Get(pObj2, 1, 1);
            XCTAssertTrue( (0 == value) );
            eRc = u16Matrix_Set(pObj2, 1, 1, 12);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 1, 1);
            XCTAssertTrue( (12 == value) );
            
            eRc = u16Matrix_Set(pObj2, 2, 1, 4);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 2, 1);
            XCTAssertTrue( (4 == value) );
            
            eRc = u16Matrix_Set(pObj2, 3, 1, 9);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 3, 1);
            XCTAssertTrue( (9 == value) );
            
            eRc = u16Matrix_Set(pObj2, 4, 1, 6);
            XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
            value = u16Matrix_Get(pObj2, 4, 1);
            XCTAssertTrue( (6 == value) );
            
            pResult = u16Matrix_Multiply(pObj, pObj2);
            XCTAssertFalse( (OBJ_NIL == pResult) );
            
            if (pResult) {
                
                value = u16Matrix_getM(pResult);
                fprintf(stderr, "m = %d need 4\n", value);
                XCTAssertTrue( (4 == value) );
                value = u16Matrix_getN(pResult);
                fprintf(stderr, "n = %d need 1\n", value);
                XCTAssertTrue( (1 == value) );
                
                value = u16Matrix_Get(pResult, 1, 1);
                fprintf(stderr, "(1,1) = %d need 15\n", value);
                XCTAssertTrue( (15 == value) );
                value = u16Matrix_Get(pResult, 2, 1);
                fprintf(stderr, "(2,1) = %d need 12\n", value);
                XCTAssertTrue( (12 == value) );
                value = u16Matrix_Get(pResult, 3, 1);
                fprintf(stderr, "(3,1) = %d need 22\n", value);
                XCTAssertTrue( (22 == value) );
                value = u16Matrix_Get(pResult, 4, 1);
                fprintf(stderr, "(4,1) = %d need 16\n", value);
                XCTAssertTrue( (16 == value) );
                
                obj_Release(pResult);
                pResult = OBJ_NIL;
            }
            
            obj_Release(pObj2);
            pObj2 = OBJ_NIL;
        }
        
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



- (void)testValueCheck01
{
    U16MATRIX_DATA	*pObj = OBJ_NIL;
    ERESULT         eRc;
    uint16_t        value = 0;
    MATRIX_BUILD    *pBuild;
    uint32_t        i = 0;
    uint32_t        iMax = 0;
    
    /*
     0 0 1 1
     1 0 0 0
     1 1 0 1
     1 1 0 0
     */
    
    pObj = u16Matrix_Alloc();
    XCTAssertFalse( (OBJ_NIL == pObj) );
    pObj = u16Matrix_Init(pObj, 4, 4);
    XCTAssertFalse( (OBJ_NIL == pObj) );
    if (pObj) {
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (0 == value) );
        
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (0 == value) );
        eRc = u16Matrix_Set(pObj, 1, 3, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 1, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 1, 4);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 2, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 2);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 3, 4, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 3, 4);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 1, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 1);
        XCTAssertTrue( (1 == value) );
        
        eRc = u16Matrix_Set(pObj, 4, 2, 1);
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(eRc)) );
        value = u16Matrix_Get(pObj, 4, 2);
        XCTAssertTrue( (1 == value) );
        
        value = u16Matrix_Get(pObj, 1, 1);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 1, 3);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 1, 4);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 2, 1);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 2, 2);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 2, 4);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 3, 1);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 3, 2);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 3, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 3, 4);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 4, 1);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 4, 2);
        XCTAssertTrue( (1 == value) );
        value = u16Matrix_Get(pObj, 4, 3);
        XCTAssertTrue( (0 == value) );
        value = u16Matrix_Get(pObj, 4, 4);
        XCTAssertTrue( (0 == value) );

        pBuild = u16Matrix_BuildValueCheck(pObj);
        XCTAssertFalse( (NULL == pBuild) );
        XCTAssertTrue( (ERESULT_IS_SUCCESSFUL(u16Matrix_getLastError(pObj))) );
        
        if (pBuild) {
            
            if (pBuild->m > pBuild->highest) {
                iMax = pBuild->m;
            }
            else {
                iMax = pBuild->highest;
            }
            fprintf(stderr, "\n\n     Base Check Value\n");
            for (i=0; i<iMax; ++i) {
                fprintf(stderr, "%3d  ", i);
                if (i+1 <= pBuild->m) {
                    fprintf(stderr, "%3d  ", pBuild->pBase[i]);
                }
                else {
                    fprintf(stderr, "     ");
                }
                if (i < pBuild->highest) {
                    fprintf(stderr, "%3d  %3d\n", pBuild->pCheck[i], pBuild->pValue[i]);
                }
                else {
                    fprintf(stderr, "\n");
                }
            }
            fprintf(stderr, "\n\n\n");

            value = valueCheckGet(pBuild, 1, 1);
            fprintf(stderr, "(1,1) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 1, 2);
            fprintf(stderr, "(1,2) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 1, 3);
            fprintf(stderr, "(1,3) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 1, 4);
            fprintf(stderr, "(1,4) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            
            value = valueCheckGet(pBuild, 2, 1);
            fprintf(stderr, "(2,1) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 2, 2);
            fprintf(stderr, "(2,2) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 2, 3);
            fprintf(stderr, "(2,3) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 2, 4);
            fprintf(stderr, "(2,4) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            
            value = valueCheckGet(pBuild, 3, 1);
            fprintf(stderr, "(3,1) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 3, 2);
            fprintf(stderr, "(3,2) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 3, 3);
            fprintf(stderr, "(3,3) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 3, 4);
            fprintf(stderr, "(3,4) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            
            value = valueCheckGet(pBuild, 4, 1);
            fprintf(stderr, "(4,1) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 4, 2);
            fprintf(stderr, "(4,2) = %d need 1\n", value);
            XCTAssertTrue( (1 == value) );
            value = valueCheckGet(pBuild, 4, 3);
            fprintf(stderr, "(4,3) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            value = valueCheckGet(pBuild, 4, 4);
            fprintf(stderr, "(4,4) = %d need 0\n", value);
            XCTAssertTrue( (0 == value) );
            
            u16Matrix_FreeValueCheck(pObj, pBuild);
            pBuild = OBJ_NIL;
        }
        
        obj_Release(pObj);
        pObj = OBJ_NIL;
    }
    
}



@end



