// vi:nu:et:sts=4 ts=4 sw=4
/* 
 * File:   compiler_internal.h
 *	Generated by 06/18/2015 11:14:11
 *
 * Notes:
 *  --	N/A
 *
 */

/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




#ifndef COMPILER_INTERNAL_H
#define	COMPILER_INTERNAL_H 1


#include    <compiler.h>
#include    <objArray.h>
#include    <node.h>

#ifdef	__cplusplus
extern "C" {
#endif





#pragma pack(push, 1)
struct compiler_data_s	{
    /* Warning - OBJ_DATA must be first in this object!
     */
    OBJ_DATA        super;
    OBJ_IUNKNOWN    *pSuperVtbl;

    // Common Data
    ERESULT         eRc;
    ERESULT_DATA    *pErrors;
    OBJ_ID          pListing;
    PATH_DATA       *pInputPath;
    PATH_DATA       *pOutputDir;
    PATH_DATA       *pTempDir;
    ASTR_DATA       *pProgramName;
    SRCFILES_DATA   *pSourceFiles;
    SZTBL_DATA      *pStringTable;
    OBJ_ID          pFileTable;
    OBJ_ID          pSymbolTable;
    NODETREE_DATA   *pParseTree;
    NODEARRAY_DATA  *pQueue0;
    NODEARRAY_DATA  *pQueue1;
    OBJARRAY_DATA   *pQueue2;
    OBJARRAY_DATA   *pQueue3;
    NODEHASH_DATA   *pProperties;
    uint8_t         fTrace;
    uint8_t         rsvd8;
    uint16_t        numErrors;

};
#pragma pack(pop)

    extern
    const
    COMPILER_VTBL   compiler_Vtbl;
    extern
    const
    struct compiler_class_data_s   compiler_ClassObj;



    // Internal Functions
    bool            compiler_setLastError(
        COMPILER_DATA   *this,
        ERESULT         value
    );
    
    
    void            compiler_Dealloc(
        OBJ_ID          objId
    );


    void *          compiler_QueryInfo(
        OBJ_ID          objId,
        uint32_t        type,
        void            *pData
    );
    
    
#ifdef NDEBUG
#else
    bool			compiler_Validate(
        COMPILER_DATA       *cbp
    );
#endif



#ifdef	__cplusplus
}
#endif

#endif	/* COMPILER_INTERNAL_H */

