// vi:nu:et:sts=4 ts=4 sw=4
/* 
 * File:   csv_internal.h
 *	Generated by 06/03/2015 09:39:47
 *
 * Notes:
 *   1	Before including define the following to customize the config bits for
 *		the development environment needed:
 *		_EXPLORER_16		Microchip Explorer 16 board
 *		_MAX32              Diligent MAX 32 board
 *		_NETWORK_SHIELD     Diligent Network Shield
 *
 * Created on September 26, 2014, 3:39 PM
 */

/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




#ifndef CSV_INTERNAL_H
#define	CSV_INTERNAL_H


#include    <csv.h>

#ifdef	__cplusplus
extern "C" {
#endif


#pragma pack(push, 1)
struct csv_data_s	{
    /* Warning - OBJ_DATA must be first in this object!
     */
    OBJ_DATA        super;
    OBJ_IUNKNOWN    *pSuperVtbl;

    // Common Data
	FILE            *fp;
	char            *fn;            /* File Name Ptr */
	char            *bf;            /* Buffer Ptr */
	uint16_t        flgs;           /* Flags */
#define CSV_ADD         0x8000          /* Data was added to file */
#define CSV_EOF         0x4000          /* EOF Reached */
#define CSV_LOCK        0x2000          /* File is Locked */
#define CSV_OPEN        0x1000          /* File is Open */
	uint16_t        pack;           /* Alignment Pack Factor */
	uint16_t        rcdLen;         /* Record Length */
	uint16_t        bufLen;         /* Buffer Size */
	uint16_t        count;          /* Number of Records */
	uint16_t        lenrcd;         /* Current Record Length */
	uint16_t        numfld;         /* Number of Fields */

    volatile
    int32_t         numRead;
    // WARNING - 'elems' must be last element of this structure!
	CSV_FIELD       fa[0];          /* Record Field Array */

};
#pragma pack(pop)

    extern
    const
    CSV_VTBL        csv_Vtbl;



    // Internal Functions
    void            csv_Dealloc(
        OBJ_ID          objId
    );

    ERESULT         csv_PutChr(
        CSV_DATA        *cbp,
        int             chr
    );
    
    
#ifdef NDEBUG
#else
    bool			csv_Validate(
        CSV_DATA       *cbp
    );
#endif



#ifdef	__cplusplus
}
#endif

#endif	/* CSV_INTERNAL_H */

