// vi:nu:et:sts=4 ts=4 sw=4
/*
 * File:   hash32.c
 *	Generated by 06/07/2015 08:07:00
 *
 * Created on December 30, 2014
 */

 
/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




//*****************************************************************
//* * * * * * * * * * * *  Data Definitions   * * * * * * * * * * *
//*****************************************************************

/* Header File Inclusion */
#include "hash32_internal.h"



#ifdef	__cplusplus
extern "C" {
#endif
    

    


 
    /****************************************************************
    * * * * * * * * * * *  Internal Subroutines   * * * * * * * * * *
    ****************************************************************/

    bool            hash32_AddBlock(
        HASH32_DATA     *this
    )
    {
        HASH32_BLOCK    *pBlock;
        uint32_t        i;
        
        // Do initialization.
        if ( NULL == this->pDeletedHead )
            ;
        else {
            return true;
        }
        
        // Get a new block.
        i = sizeof(HASH32_BLOCK) + (this->cBlock * sizeof(HASH32_NODE));
        pBlock = (HASH32_BLOCK *)mem_Malloc( i );
        if( NULL == pBlock ) {
            return false;
        }
        pBlock->pNext = this->pBlocks;
        this->pBlocks = pBlock;
        
        // Now chain the entries to the Deleted chain.
        for (i=0; i<this->cBlock; ++i) {
            pBlock->node[i].pNext = this->pDeletedHead;
            this->pDeletedHead = &pBlock->node[i];
        }
        
        // Return to caller.
        return true;
    }
    
    
    
    HASH32_NODE *   hash32_FindEntry(
        HASH32_DATA     *this,
        uint32_t        key
    )
    {
        HASH32_NODE     *pNode;
        
        // Do initialization.
        pNode = hash32_NodeFromKey(this, key);
        
        while (pNode) {
            if (pNode->key == key) {
                return pNode;
            }
            pNode = pNode->pNext;
        }
        
        // Return to caller.
        return NULL;
    }
    
    
    
    uint16_t        hash32_IndexFromKey(
        HASH32_DATA     *this,
        uint32_t        key
    )
    {
        uint16_t        index;
        
        index = key % this->cHash;
        return index;
    }
    
    
    
    HASH32_NODE *   hash32_NodeFromKey(
        HASH32_DATA     *this,
        uint32_t        key
    )
    {
        HASH32_NODE     *pNode;
        
        pNode = this->pHash[hash32_IndexFromKey(this, key)];
        return( pNode );
    }
    
    
    

    /****************************************************************
    * * * * * * * * * * *  External Subroutines   * * * * * * * * * *
    ****************************************************************/


    //===============================================================
    //                      *** Class Methods ***
    //===============================================================

    HASH32_DATA *     hash32_Alloc(
    )
    {
        HASH32_DATA     *this;
        uint32_t        cbSize = sizeof(HASH32_DATA);
        
        // Do initialization.
        
        this = obj_Alloc( cbSize );
        
        // Return to caller.
        return this;
    }



    

    //===============================================================
    //                      P r o p e r t i e s
    //===============================================================

    uint32_t        hash32_getCount(
        HASH32_DATA     *this
    )
    {

        // Validate the input parameters.
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
        }
#endif

        return this->num;
    }



    

    //===============================================================
    //                          M e t h o d s
    //===============================================================


    //----------------------------------------------------------
    //                          A d d
    //----------------------------------------------------------
    
    bool            hash32_Add(
        HASH32_DATA     *this,
        uint32_t        key,
        void			*pData
    )
    {
        HASH32_NODE     *pNode;
        uint16_t        index;
        
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return false;
        }
#endif
        
        if (hash32_FindEntry(this, key)) {
            return false;
        }
        
        // Determine the entry number.
        if ( hash32_AddBlock(this) )
            ;
        else {
            return false;
        }
        pNode = this->pDeletedHead;
        this->pDeletedHead = pNode->pNext;
        
        // Add it to the table.
        pNode->key = key;
        pNode->pData = pData;
        index = hash32_IndexFromKey(this, key);
        pNode->pNext = this->pHash[index];
        this->pHash[index] = pNode;
        ++this->num;
        
        // Return to caller.
        return true;
    }
    
    
        
    //---------------------------------------------------------------
    //                        D e a l l o c
    //---------------------------------------------------------------

    void            hash32_Dealloc(
        OBJ_ID          objId
    )
    {
        HASH32_DATA     *this = objId;
        HASH32_BLOCK    *pBlock;
        HASH32_BLOCK    *pBlockNext;

        // Do initialization.
        if (NULL == this) {
            return;
        }        
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return;
        }
#endif

        if( this->pBlocks ) {
            pBlock = this->pBlocks;
            while (pBlock) {
                pBlockNext = pBlock->pNext;
                mem_Free( pBlock );
                pBlock = pBlockNext;
            }
        }
        
        if( this->pHash ) {
            mem_Free( this->pHash );
            this->pHash = NULL;
        }
        
        obj_setVtbl(this, (OBJ_IUNKNOWN *)this->pSuperVtbl);
        obj_Dealloc(this);
        this = NULL;

        // Return to caller.
    }



    //----------------------------------------------------------
    //					  D e l e t e
    //----------------------------------------------------------
    
    /* Delete() closes down the file, deletes it and frees all
     * memory used.  It is used in lieu of HASH_Close().
     */
    
    bool            hash32_Delete(
        HASH32_DATA     *this,
        uint32_t        key
    )
    {
        HASH32_NODE     *pNode;
        HASH32_NODE     *pNodePrev = OBJ_NIL;
        uint16_t        index;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return 0;
        }
#endif
        
        index = hash32_IndexFromKey(this, key);
        if (this->pHash[index]) {
            pNode = this->pHash[index];
            if (pNode->key == key) {
                this->pHash[index] = pNode->pNext;
                pNode->pNext = this->pDeletedHead;
                this->pDeletedHead = pNode;
                --this->num;
                return true;
            }
        }
        else {
            return false;
        }
        while (pNode && (pNode->key != key)) {
            pNodePrev = pNode;
            pNode = pNode->pNext;
        }
        
        if (NULL == pNode) {
            return false;
        }
        
        // Delete the node.
        pNodePrev->pNext = pNode->pNext;
        pNode->pNext = this->pDeletedHead;
        this->pDeletedHead = pNode;
        --this->num;
        
        // Return to caller.
        return true;
    }
    
    
    
    //----------------------------------------------------------
    //                        F i n d
    //----------------------------------------------------------
    
    void *          hash32_Find(
        HASH32_DATA     *this,
        uint32_t        key
    )
    {
        HASH32_NODE     *pNode;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return NULL;
        }
#endif
        
        pNode = hash32_FindEntry(this, key);
        if (pNode) {
            return pNode->pData;
        }
        
        // Return to caller.
        return NULL;
    }
    
    
    
    //---------------------------------------------------------------
    //                          I n i t
    //---------------------------------------------------------------

    HASH32_DATA *   hash32_Init(
        HASH32_DATA     *this,
        uint16_t        cHash           // Hash Table Size (Prime Number)
    )
    {
        uint16_t        cbSize;
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        this = obj_Init( this, obj_getSize(this), OBJ_IDENT_HASH32 );
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        this->pSuperVtbl = obj_getVtbl(this);
        obj_setVtbl(this, (OBJ_IUNKNOWN *)&hash32_Vtbl);
        
        // Initialize the fields.
        cbSize = 4096 - sizeof(HASH32_BLOCK);
        cbSize /= sizeof(HASH32_NODE);
        this->cBlock = cbSize;
        this->cHash = cHash;
        
        // Allocate the Hash Table.
        cbSize = cHash * sizeof(HASH32_NODE *);
        this->pHash = (HASH32_NODE **)mem_Malloc( cbSize );
        if(NULL == this->pHash) {
            DEBUG_BREAK();
            obj_Release(this);
            this = OBJ_NIL;
            return this;
        }
        memset(this->pHash, 0, cbSize);
        
#ifdef NDEBUG
    #else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
        BREAK_NOT_BOUNDARY4(sizeof(HASH32_DATA));
    #endif

        return this;
    }

     

    //----------------------------------------------------------
    //					  U p d a t e
    //----------------------------------------------------------
    
    bool            hash32_Update(
        HASH32_DATA     *this,
        uint32_t        key,
        void            *pData
    )
    {
        HASH32_NODE     *pNode;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !hash32_Validate(this) ) {
            DEBUG_BREAK();
            return 0;
        }
#endif
        
        pNode = hash32_FindEntry(this, key);
        if (pNode) {
            pNode->pData = pData;
        }
        else
            return false;
        
        // Return to caller.
        return true;
    }
    
    
    
    //---------------------------------------------------------------
    //                      V a l i d a t e
    //---------------------------------------------------------------

    #ifdef NDEBUG
    #else
    bool            hash32_Validate(
        HASH32_DATA      *this
    )
    {
        if(this) {
            if ( obj_IsKindOf(this, OBJ_IDENT_HASH32) )
                ;
            else
                return false;
        }
        else
            return false;
        if( !(obj_getSize(this) >= sizeof(HASH32_DATA)) )
            return false;

        // Return to caller.
        return true;
    }
    #endif


    
    
    
#ifdef	__cplusplus
}
#endif


