// vi:nu:et:sts=4 ts=4 sw=4
/*
 * File:   W32Str.c
 *	Generated by 06/08/2015 18:39:43
 *
 * Created on December 30, 2014
 *
 *
 * NOTE --
 *  The underlying structure, array, has no knowledge of the extra
 *  NUL-terminator on the string. So, it must be accounted for in these
 *  routines. Since array is a simple array, it might be that you
 *  allocate strlen+1 for new data.
 *
 */

 
/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




//*****************************************************************
//* * * * * * * * * * * *  Data Definitions   * * * * * * * * * * *
//*****************************************************************

/* Header File Inclusion */
#include        <W32Str_internal.h>
#include        <ascii.h>
#include        <str.h>
#include        <crc.h>
#include        <dec.h>
#include        <hex.h>
#include        <Node.h>
#include        <NodeHash.h>
#include        <utf8.h>
#include        <stdio.h>
#include        <time.h>



#ifdef	__cplusplus
extern "C" {
#endif

    
    
    /*
     
     size_t    strcspn(const char *str1, const char *str2)
     
     Calculates the length of the initial segment of str1 which 
     consists entirely of characters not in str2.

     
     char *    strpbrk(const char *str1, const char *str2)
     
     Finds the first character in the string str1 that 
     matches any character specified in str2.

     
     size_t    strspn(const char *str1, const char *str2)
     
     Calculates the length of the initial segment of str1 
     which consists entirely of characters in str2.
     
     

     */


 
    /****************************************************************
    * * * * * * * * * * *  Internal Subroutines   * * * * * * * * * *
    ****************************************************************/

#ifdef XYZZY
    typedef struct RE {
        int     type;   /* CHAR, STAR, etc. */
        char    ch;     /* the character itself */
        char    *ccl;   /* for [...] instead */
        int     nccl;   /* true if class is negated [^...] */
    } RE;
    
    /* match: search for regexp anywhere in text */
    int         match(
                      char        *regexp,
                      char        *text
                      )
    {
        if (regexp[0] == '^')
            return matchhere(regexp+1, text);
        do {    /* must look even if string is empty */
            if (matchhere(regexp, text))
                return 1;
        } while (*text++ != '\0');
        return 0;
    }
    
    
    /* matchhere: search for regexp at beginning of text */
    int         matchhere(
                          char        *regexp,
                          char        *text
                          )
    {
        if (regexp[0] == '\0')
            return 1;
        if (regexp[1] == '*')
            return matchstar(regexp[0], regexp+2, text);
        if ((regexp[0] == '$') && (regexp[1] == '\0'))
            return (*text == '\0');
        if ((*text != '\0') && ((regexp[0] == '.') || (regexp[0] == *text)))
            return matchhere(regexp+1, text+1);
        return 0;
    }
    
    
    /* matchstar: search for c*regexp at beginning of text */
    int         matchstar(
                          int         c,
                          char        *regexp,
                          char        *text
                          )
    {
        do {    /* a * matches zero or more instances */
            if (matchhere(regexp, text))
                return 1;
        } while (*text != '\0' && (*text++ == c || c == '.'));
        return 0;
    }
#endif
    
    
    
    
    
    

    /****************************************************************
    * * * * * * * * * * *  External Subroutines   * * * * * * * * * *
    ****************************************************************/


    //===============================================================
    //                      *** Class Methods ***
    //===============================================================

    W32STR_DATA *   W32Str_Alloc(
    )
    {
        W32STR_DATA     *this;
        uint32_t        cbSize = sizeof(W32STR_DATA);
        
        // Do initialization.
        
        this = obj_Alloc( cbSize );
        
        // Return to caller.
        return this;
    }



    // Return offset of chr in string (relative to 1)
    // Returns 0 if not found.
    uint32_t        W32Str_ChrInStr(
        W32CHR_T        chr,
        const
        W32CHR_T        *pStr
    )
    {
        uint32_t        index = 1;
        
        while (*pStr) {
            if (*pStr == chr) {
                return index;
            }
            ++pStr;
            ++index;
        }
        
        return 0;
    }
    
    
    
    int             W32Str_Cmp(
        const
        W32CHR_T        *pStr1,
        const
        W32CHR_T        *pStr2
    )
    {
        //ERESULT         eRc = ERESULT_SUCCESS_EQUAL;
        int             i = 0;
        
        for( ;; ) {
            if( *pStr1 )
                ;
            else {
                if( *pStr2 )
                    //eRc = ERESULT_SUCCESS_LESS_THAN;
                    i = -1;
                break;
            }
            if( *pStr2 )
                ;
            else {
                if( *pStr1 )
                    //eRc = ERESULT_SUCCESS_GREATER_THAN;
                    i = 1;
                break;
            }
            i = *pStr1 - *pStr2;
            if( i ) {
                break;
            }
            ++pStr1;
            ++pStr2;
        }
        if (i < 0)
            i = -1;
        else if (i > 0)
            i = 1;
        
        // Return to caller.
        return i;
    }
    
    
    
    uint32_t        W32Str_StrLen(
        const
        W32CHR_T        *pData
    )
    {
        uint32_t        len = 0;
        
        while (*pData++) {
            ++len;
        }
        
        return len;
    }
    
    
    
    W32STR_DATA *     W32Str_New(
    )
    {
        W32STR_DATA       *this;
        
        this = W32Str_Alloc( );
        this = W32Str_Init(this);
        
        // Return to caller.
        return this;
    }
    
    
    
    W32STR_DATA *     W32Str_NewA(
        const
        char            *pStrA
    )
    {
        W32STR_DATA       *this;
        ERESULT         eRc;
        int32_t         len;
        
        // Do initialization.
        if (NULL == pStrA) {
            return OBJ_NIL;
        }
        
        this = W32Str_Alloc( );
        this = W32Str_Init(this);
        if (this) {
            len = utf8_StrLenA(pStrA);
            if (len) {
                eRc = W32Str_AppendA(this, pStrA);
                if (ERESULT_HAS_FAILED(eRc)) {
                    obj_Release(this);
                    this = OBJ_NIL;
                }
            }
        }
        
        // Return to caller.
        return this;
    }
    
    
    
    W32STR_DATA *     W32Str_NewW32(
        uint32_t        len,
        const
        W32CHR_T        *pStr
    )
    {
        W32STR_DATA       *this;
        ERESULT         eRc;
        
        // Do initialization.
        if (NULL == pStr) {
            return OBJ_NIL;
        }
        
        this = W32Str_Alloc( );
        this = W32Str_Init(this);
        if (this) {
            eRc = W32Str_AppendW32(this, len, pStr);
            if (ERESULT_HAS_FAILED(eRc)) {
                obj_Release(this);
                this = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return this;
    }
    
    
    
    W32STR_DATA *     W32Str_NewFromEnv(
        const
        char            *pStrA
    )
    {
        W32STR_DATA       *this =  OBJ_NIL;
        char            *pData;
        size_t          len;
        
        // Do initialization.
        if (NULL == pStrA) {
            return this;
        }
        
        pData = getenv(pStrA);
        if (NULL == pData)
            ;
        else {
            len = strlen(pData);
            if (len) {
                this = W32Str_NewA(pData);
            }
        }
        
        // Return to caller.
        return this;
    }
    
    
    
    W32STR_DATA *     W32Str_NewFromUtf8File(
        PATH_DATA       *pPath
    )
    {
        W32STR_DATA       *this =  OBJ_NIL;
        ERESULT         eRc;
        
        // Do initialization.
        if (NULL == pPath) {
            return this;
        }
        
        this = W32Str_New( );
        if (this) {
            eRc = W32Str_AppendUtf8File(this, pPath);
            if (ERESULT_FAILED(eRc)) {
                obj_Release(this);
                this = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return this;
    }
    
    
    
    W32STR_DATA *     W32Str_NewFromTimeNow(
    )
    {
        W32STR_DATA       *this =  OBJ_NIL;
        time_t			startTime;
        char            timeStr[20];
        
        
        // Do initialization.
        startTime = time(NULL);
        strftime( timeStr, 20, "%Y-%m-%d %H:%M:%S", localtime(&startTime) );
        
        this = W32Str_NewA(timeStr);
        
        // Return to caller.
        return this;
    }
    
    
    
    

    

    //===============================================================
    //                      P r o p e r t i e s
    //===============================================================

    uint32_t        W32Str_getCrcIEEE(
        W32STR_DATA       *this
    )
    {
        CRC_DATA        *pCrc = OBJ_NIL;
        uint32_t        crc = 0;
        uint32_t        len;
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
        }
#endif
        
        pCrc = crc_New(CRC_TYPE_IEEE_32);
        len = array_getSize((ARRAY_DATA *)this);
        crc =   crc_AccumBlock(
                    pCrc,
                    (len * sizeof(int32_t)),
                    (void *)array_Ptr((ARRAY_DATA *)this, 1)
                 );
        obj_Release(pCrc);
        pCrc = OBJ_NIL;
        
        return  crc;
    }
    
    
    
    const
    W32CHR_T *      W32Str_getData(
        W32STR_DATA       *this
    )
    {
        W32CHR_T        *pData;

        // Validate the input parameters.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
        }
#endif

        pData = array_Ptr((ARRAY_DATA *)this, 1);
        
        return pData;
    }


    uint32_t        W32Str_getLength(
        W32STR_DATA       *this
    )
    {
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
        }
#endif
        return array_getSize((ARRAY_DATA *)this) - 1;
    }




    

    //===============================================================
    //                          M e t h o d s
    //===============================================================


    //---------------------------------------------------------------
    //                       A p p e n d
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Append(
        W32STR_DATA		*this,
        W32STR_DATA       *pOther
    )
    {
        ERESULT         eRc = ERESULT_SUCCESS;
        uint32_t        len = array_getSize((ARRAY_DATA *)this);
        uint32_t        len2add = array_getSize((ARRAY_DATA *)pOther);

        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif

        if (len2add > 1) {
            eRc =   array_InsertData(
                                (ARRAY_DATA *)this,
                                len,
                                (len2add - 1),
                                array_getData((ARRAY_DATA *)pOther)
                    );
            if (ERESULT_IS_SUCCESSFUL(eRc)) {
                array_AdjustSize((ARRAY_DATA *)this, -1);
            }
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    ERESULT         W32Str_AppendA(
        W32STR_DATA		*this,
        const
        char            *pStrA
    )
    {
        ERESULT         eRc;
        W32CHR_T        chr;
        uint32_t        i;
        uint32_t        len;
        uint32_t        index;
        W32CHR_T        *pInsert;
        
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        
        len = (uint32_t)utf8_StrLenA(pStrA);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
       
        index = array_getSize((ARRAY_DATA *)this);
        eRc =   array_InsertSpacing(
                    (ARRAY_DATA *)this,
                    index,
                    len
                );
        
        // Copy the data converting UTF-8 to UTF-32.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = array_Ptr((ARRAY_DATA *)this, index);
            for (i=0; i<len; ++i) {
                chr = utf8_Utf8ToW32_Scan(&pStrA);
                *pInsert++ = chr;
            }
            *pInsert = '\0';
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    ERESULT         W32Str_AppendStrA(
        W32STR_DATA		*this,
        ASTR_DATA       *pStr
    )
    {
        ERESULT         eRc;
        W32CHR_T        chr;
        uint32_t        i;
        uint32_t        len;
        uint32_t        index;
        W32CHR_T        *pInsert;
        const
        char            *pText;
        
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        
        len = AStr_getLength(pStr);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
        pText = AStr_getData(pStr);
        
        index = array_getSize((ARRAY_DATA *)this);
        eRc =   array_InsertSpacing((ARRAY_DATA *)this, index, len);
        
        // Copy the data.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = array_Ptr((ARRAY_DATA *)this, index);
            for (i=0; i<len; ++i) {
                chr = AStr_CharGetW32(pStr, (i+1));
                *pInsert++ = chr;
            }
            *pInsert = '\0';
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    ERESULT         W32Str_AppendW32(
        W32STR_DATA		*this,
        uint32_t        len,
        const
        W32CHR_T        *pStr
    )
    {
        ERESULT         eRc = ERESULT_DATA_MISSING;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        if (0 == len) {
            len = W32Str_StrLen(pStr);
        }
        if (len) {
            eRc =   array_InsertData(
                            (ARRAY_DATA *)this,
                            array_getSize((ARRAY_DATA *)this),
                            len,
                            (void *)pStr
                    );
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       A p p e n d  C h a r
    //---------------------------------------------------------------
    
    ERESULT         W32Str_AppendCharW32(
        W32STR_DATA		*this,
        uint32_t        len,
        const
        W32CHR_T        chr
    )
    {
        W32CHR_T        *pData;
        uint32_t        offset;
        uint32_t        i;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
        if (0 == len) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        offset = array_getSize((ARRAY_DATA *)this);
        eRc =   array_InsertSpacing(
                        (ARRAY_DATA *)this,
                        offset,
                        len
                );
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pData = array_Ptr( (ARRAY_DATA *)this, offset);
            for (i=0; i<len; ++i) {
                *pData++ = chr;
            };
            //*pData = '\0';
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                    A p p e n d  F i l e
    //---------------------------------------------------------------
    
    ERESULT         W32Str_AppendUtf8File(
        W32STR_DATA		*this,
        PATH_DATA       *pPath
    )
    {
        ERESULT         eRc = ERESULT_GENERAL_FAILURE;
        W32CHR_T        chr;
        FILE            *pFile;
        
        /* Do Initialization.
         */
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( OBJ_NIL == pPath ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        pFile = fopen(Path_getData(pPath), "r");
        if (NULL == pFile) {
            return ERESULT_FILE_NOT_FOUND;
        }
        while ( (chr = fgetwc(pFile)) != EOF ) {
            eRc = W32Str_AppendCharW32(this, 1, chr);
            if (ERESULT_FAILED(eRc)) {
                DEBUG_BREAK();
                return eRc;
            }
        }
        fclose(pFile);
        pFile = NULL;
        
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                    A p p e n d  P r i n t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_AppendPrintA(
        W32STR_DATA		*this,
        const
        char            *pFormat,
        ...
    )
    {
        ERESULT         eRc;
        int             size;
        va_list         arg_ptr;
        char            *pStr = NULL;
        
        /* Do Initialization.
         */
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        va_start( arg_ptr, pFormat );
        size = vsnprintf( NULL, 0, pFormat, arg_ptr );
        va_end( arg_ptr );
        ++size;
        pStr = (char *)mem_Malloc( size );
        if( pStr == NULL ) {
            return ERESULT_INSUFFICIENT_MEMORY;
        }
        va_start( arg_ptr, pFormat );
        size = vsnprintf( pStr, size, pFormat, arg_ptr );
        va_end( arg_ptr );
        eRc = W32Str_AppendA(this, pStr);
        mem_Free( pStr );
        pStr = NULL;
        
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       A s s i g n
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Assign(
        W32STR_DATA		*this,
        W32STR_DATA       *pOther
    )
    {
        ERESULT         eRc = ERESULT_SUCCESS;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( !W32Str_Validate( pOther ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif

        eRc = array_Assign((ARRAY_DATA *)this, (ARRAY_DATA *)pOther);
        if (ERESULT_HAS_FAILED(eRc)) {
            return eRc;
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //               C h a r  F i n d  N e x t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_CharFindNextW32(
        W32STR_DATA		*this,
        uint32_t        *pIndex,
        const
        W32CHR_T        chr
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }

        pChr = array_Ptr((ARRAY_DATA *)this, index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (chr == *pChr) {
                *pIndex = i;
                return ERESULT_SUCCESS;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    

    
    //---------------------------------------------------------------
    //               C h a r  F i n d  P r e v
    //---------------------------------------------------------------
    
    ERESULT         W32Str_CharFindPrevW32(
        W32STR_DATA		*cbp,
        uint32_t        *pIndex,
        const
        W32CHR_T        chr
    )
    {
        uint32_t        i;
        uint32_t        index;
        W32CHR_T        *pChr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        index = *pIndex;
        if (0 == index) {
            index = lenStr;
        }
        if (index > lenStr) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)cbp, index);
        for ( i=index; i; --i,--pChr ) {
            if (chr == *pChr) {
                *pIndex = i;
                return ERESULT_SUCCESS;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C h a r  G e t
    //---------------------------------------------------------------
    
    W32CHR_T        W32Str_CharGetW32(
        W32STR_DATA		*cbp,
        uint32_t        offset
    )
    {
        W32CHR_T        *pSrc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return -1;
        }
#endif
        if ((0 == offset)
            || (offset > (array_getSize((ARRAY_DATA *)cbp))-1)) {
            return -1;
        }
        
        pSrc = array_Ptr((ARRAY_DATA *)cbp, offset);
        
        // Return to caller.
        return *pSrc;
    }
    
    
    
    //---------------------------------------------------------------
    //               C h a r  R e p l a c e  A l l
    //---------------------------------------------------------------
    
    ERESULT         W32Str_CharReplaceAllW32(
        W32STR_DATA		*cbp,
        const
        W32CHR_T        chrSrch,
        const
        W32CHR_T        chrRepl
    )
    {
        uint32_t        i;
        W32CHR_T        *pChr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        
        pChr = array_Ptr((ARRAY_DATA *)cbp, 1);
        for ( i=0; i<lenStr; ++i,++pChr ) {
            if (*pChr == chrSrch) {
                *pChr = chrRepl;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C h a r  P u t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_CharPutW32(
        W32STR_DATA		*cbp,
        uint32_t        offset,
        const
        W32CHR_T        chr
    )
    {
        uint32_t        lenStr;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return false;
        }
#endif
        lenStr = W32Str_getLength(cbp);

        if ((0 == offset) || (offset > array_getSize((ARRAY_DATA *)cbp))) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)cbp, offset);
        *pChr = chr;
        
        // Return to caller.
        return true;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C l e a n  D i r
    //---------------------------------------------------------------
    
    ERESULT         W32Str_CleanDir(
        W32STR_DATA		*cbp
    )
    {
        //uint32_t        i;
        //uint32_t        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return false;
        }
#endif
        if (0 == array_getSize((ARRAY_DATA *)cbp)) {
            return ERESULT_SUCCESS;
        }
        
#ifdef XYZZY        //TODO: Fix this!
        for (i=0,pChr=cbp->pData; i<array_getSize((ARRAY_DATA *)cbp); ++i,++pChr) {
            if ((cbp->length - i) >= 2) {
                if( (*pChr == '/') && (*(pChr+1) == '/') ) {
                    memmove(pChr, pChr+1, (cbp->length - i - 1));
                    --cbp->length;
                    continue;
                }
            }
            if ((cbp->length - i) >= 3) {
                if( (*pChr == '/') && (*(pChr+1) == '.') && (*(pChr+2) == '/') ) {
                    memmove(pChr, pChr+2, (cbp->length - i - 2));
                    --cbp->length;
                    --cbp->length;
                    continue;
                }
            }
        }
        
        if( (cbp->length >= 3)
            && (cbp->pData[cbp->length-3] == '/')
            && (cbp->pData[cbp->length-2] == '.')
            && (cbp->pData[cbp->length-1] == '/')
        ) {
            memmove(pChr, pChr+2, (cbp->length - i - 2));
            --cbp->length;
            --cbp->length;
        }
        
        while ( (cbp->pData[cbp->length-1] == '/') && (cbp->length > 1) ) {
            --cbp->length;
        }
        cbp->pData[cbp->length] = '\0';
#endif
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C o m p a r e
    //---------------------------------------------------------------
    
    int             W32Str_Compare(
        W32STR_DATA		*cbp,
        W32STR_DATA     *pOther
    )
    {
        //ERESULT         eRc = ERESULT_SUCCESS_EQUAL;
        int             i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            //return ERESULT_INVALID_OBJECT;
            return -2;
        }
        if( !W32Str_Validate( pOther ) ) {
            DEBUG_BREAK();
            //return ERESULT_INVALID_OBJECT;
            return -2;
        }
#endif
        if( OBJ_NIL == pOther ) {
            DEBUG_BREAK();
            //return ERESULT_SUCCESS_GREATER_THAN;
            return 1;
        }

        i = W32Str_CompareW32(cbp, array_Ptr((ARRAY_DATA *)pOther,1));
        
        // Return to caller.
        return i;
    }
    
    
    int             W32Str_CompareA(
        W32STR_DATA		*this,
        const
        char            *pString
    )
    {
        //ERESULT         eRc = ERESULT_SUCCESS_EQUAL;
        uint32_t        str1len;
        const
        W32CHR_T        *pStr1;
        uint32_t        str2len;
        W32CHR_T        chr2;
        int             i = -1;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            //return ERESULT_INVALID_OBJECT;
            return -2;
        }
#endif
        
        str1len = W32Str_getLength(this);
        pStr1 = array_Ptr((ARRAY_DATA *)this, 1);
        if (NULL == pString) {
            str2len = 0;
        }
        else {
            str2len = (uint32_t)utf8_StrLenA(pString);
        }
        
        if ((0 == str1len) && (0 == str2len)) {
            return 0;
        }

        for( ;; ) {
            chr2 = utf8_Utf8ToW32_Scan(&pString);
            if( *pStr1 )
                ;
            else {
                if( chr2 )
                    //eRc = ERESULT_SUCCESS_LESS_THAN;
                    i = -1;
                break;
            }
            if( chr2 )
                ;
            else {
                if( *pStr1 )
                    //eRc = ERESULT_SUCCESS_GREATER_THAN;
                    i = 1;
                break;
            }
            i = *pStr1 - chr2;
            if( i ) {
                break;
            }
            ++pStr1;
        }
        if (i < 0)
            i = -1;
        else if (i > 0)
            i = 1;
        
        // Return to caller.
        return i;
    }
    
    
    int             W32Str_CompareW32(
        W32STR_DATA		*this,
        const
        W32CHR_T        *pString
    )
    {
        //ERESULT         eRc = ERESULT_SUCCESS_EQUAL;
        uint32_t        str1len;
        const
        W32CHR_T        *pStr1;
        uint32_t        str2len;
        const
        W32CHR_T        *pStr2;
        int             i = -1;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            //return ERESULT_INVALID_OBJECT;
            return -2;
        }
#endif
        
        str1len = W32Str_getLength(this);
        pStr1 = array_Ptr((ARRAY_DATA *)this, 1);
        if (NULL == pString) {
            str2len = 0;
            pStr2 = NULL;
        }
        else {
            str2len = (uint32_t)W32Str_StrLen(pString);
            pStr2 = pString;
        }
        
        if ((0 == str1len) && (0 == str2len)) {
            return 0;
        }

        for( ;; ) {
            if( *pStr1 )
                ;
            else {
                if( *pStr2 )
                    //eRc = ERESULT_SUCCESS_LESS_THAN;
                    i = -1;
                break;
            }
            if( *pStr2 )
                ;
            else {
                if( *pStr1 )
                    //eRc = ERESULT_SUCCESS_GREATER_THAN;
                    i = 1;
                break;
            }
            i = *pStr1 - *pStr2;
            if( i ) {
                break;
            }
            ++pStr1;
            ++pStr2;
        }
        if (i < 0)
            i = -1;
        else if (i > 0)
            i = 1;

        // Return to caller.
        return i;
    }
    
    
    
    //---------------------------------------------------------------
    //                          C o p y
    //---------------------------------------------------------------
    
    W32STR_DATA *     W32Str_Copy(
        W32STR_DATA		*cbp
    )
    {
        W32STR_DATA       *pOther;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
#endif
        
        pOther = W32Str_New();
        if (pOther) {
            eRc = W32Str_Assign(cbp, pOther);
            if (ERESULT_HAS_FAILED(eRc)) {
                obj_Release(pOther);
                pOther = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return pOther;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C S t r i n g A
    //---------------------------------------------------------------
    
    char *          W32Str_CStringA(
        W32STR_DATA		*this,
        uint32_t        *pLen       // Optional returned string length
                                    // less terminating NUL
    )
    {
        char            *pszStr;
        uint32_t        lenStr;
        uint32_t        lenA = 0;
        uint32_t        i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return NULL;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        lenA =  utf8_W32StrToUtf8Str(
                            lenStr,
                            array_Ptr((ARRAY_DATA *)this, 1),
                            0,
                            NULL
                );
        pszStr = (char *)mem_Malloc(lenA);
        if (pszStr) {
            i =     utf8_W32StrToUtf8Str(
                                     lenStr,
                                     array_Ptr((ARRAY_DATA *)this, 1),
                                     lenA,
                                     pszStr
                                     );
            if (i<lenA) {
            }
            else {
                mem_Free(pszStr);
                return NULL;
            }
        }
        
        // Return to caller.
        if (pLen) {
            *pLen = lenA - 1;
        }
        return pszStr;
    }
    
    
    
    //---------------------------------------------------------------
    //                        D e a l l o c
    //---------------------------------------------------------------

    void            W32Str_Dealloc(
        OBJ_ID          objId
    )
    {
        W32STR_DATA       *this = objId;

        // Do initialization.
        if (NULL == this) {
            return;
        }        
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return;
        }
#endif

        obj_setVtbl(this, this->pSuperVtbl);
        // pSuperVtbl is saved immediately after the super
        // object which we inherit from is initialized.
        this->pSuperVtbl->pDealloc(this);
        this = OBJ_NIL;

        // Return to caller.
    }



    //---------------------------------------------------------------
    //                     E s c a p e  F o r  C
    //---------------------------------------------------------------
    
    ERESULT         W32Str_EscapeForC(
        W32STR_DATA		*this
    )
    {
        ERESULT         eRc = ERESULT_SUCCESS;
        W32CHR_T        chrEscape = '\\';
        W32CHR_T        *pData;
        uint32_t        lenStr;
        uint32_t        i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        // The order matters in how we do these replacements.
       
        for (i=1; i<=W32Str_getLength(this); ++i) {
            pData = (W32CHR_T *)array_Ptr((ARRAY_DATA *)this, i);
            if (pData) {
                if (*pData == chrEscape) {
                    array_InsertData((ARRAY_DATA *)this, i, 1, &chrEscape);
                    i += 1;
                }
            }
        }
        
        for (i=1; i<=W32Str_getLength(this); ++i) {
            pData = (W32CHR_T *)array_Ptr((ARRAY_DATA *)this, i);
            if (pData) {
                if (*pData == '"') {
                    array_InsertData((ARRAY_DATA *)this, i, 1, &chrEscape);
                    i += 1;
                }
                else if (*pData == '\n') {
                    *pData = 'n';
                    array_InsertData((ARRAY_DATA *)this, i, 1, &chrEscape);
                    i += 1;
                }
                else if (*pData == '\r') {
                    *pData = 'r';
                    array_InsertData((ARRAY_DATA *)this, i, 1, &chrEscape);
                    i += 1;
                }
                else if (*pData == '\t') {
                    *pData = 't';
                    array_InsertData((ARRAY_DATA *)this, i, 1, &chrEscape);
                    i += 1;
                }
            }
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                  E x p a n d  V a r i a b l e s
    //---------------------------------------------------------------
    
    /*!
     Substitute hash values or environment variables into the current string
     using a BASH-like syntax with the hash value having the highest priority.
     Variable names should have the syntax of:
     '$' '{'[a-zA-Z_][a-zA-Z0-9_]* '}'.
     Substitutions are not rescanned after insertion.
     @param     this    object pointer
     @param     pHash   optional node hash pointer where the node's data is a
     path or astr kind object.
     @return    ERESULT_SUCCESS if successful.  Otherwise, an ERESULT_* error code
     is returned.
     */
    ERESULT         W32Str_ExpandVars(
        W32STR_DATA     *this,
        OBJ_ID          pHash
    )
    {
        ERESULT         eRc;
        uint32_t        i = 0;
        uint32_t        j;
        uint32_t        len;
        bool            fMore = true;
        //PATH_DATA       *pPath = OBJ_NIL;
        ASTR_DATA       *pName = OBJ_NIL;
        const
        char            *pEnvVar = NULL;
        NODE_DATA       *pNode = OBJ_NIL;
        OBJ_ID          pData;
        W32CHR_T        *pChr;
        W32CHR_T        chr;

        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (pHash) {
            if(obj_IsKindOf(pHash, OBJ_IDENT_NODEHASH))
                ;
            else {
                DEBUG_BREAK();
                return ERESULT_INVALID_PARAMETER;
            }
        } else {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        if (pHash)
            return ERESULT_NOT_IMPLEMENTED;

        
        if (0 == W32Str_getLength(this)) {
            return ERESULT_SUCCESS;
        }
        pChr = array_Ptr((ARRAY_DATA *)this, 1);

        // Expand Environment variables.
        while (fMore) {
            fMore = false;
            eRc = W32Str_CharFindNextW32(this, &i, '$');
            if (ERESULT_FAILED(eRc)) {
                break;
            }
            else {
                chr = W32Str_CharGetW32(this, i+1);
                if (chr == '{') {
                    i += 2;
                    j = i;
                    eRc = W32Str_CharFindNextW32(this, &j, '}');
                    if (ERESULT_FAILED(eRc)) {
                        return ERESULT_PARSE_ERROR;
                    }
                    len = j - i;
                    //FIXME: eRc = W32Str_Mid(this, i, len, &pName);
                    if (ERESULT_FAILED(eRc)) {
                        return ERESULT_OUT_OF_MEMORY;
                    }
                    if (pHash) {
                        pNode = NodeHash_FindA(pHash, 0, AStr_getData(pName));
                        if (pNode) {
                            pData = Node_getData(pNode);
                            if (obj_IsKindOf(this, OBJ_IDENT_ASTR)
                                || obj_IsKindOf(this, OBJ_IDENT_PATH)) {
                                pEnvVar = AStr_getData((ASTR_DATA *)pData);
                            }
                            else if (obj_IsKindOf(this, OBJ_IDENT_ASTRC)) {
                                pEnvVar = AStrC_getData((ASTRC_DATA *)pData);
                            }
                            if (pNode && pEnvVar) {
                                goto expandIt;
                            }
                            // We did not find it in the Hash. So, fall
                            // through to normal environment variables
                            // search.
                        }
                    }
                    pEnvVar = getenv(AStr_getData(pName));
                    if (NULL == pEnvVar) {
                        obj_Release(pName);
                        return ERESULT_DATA_NOT_FOUND;
                    }
                expandIt:
                    obj_Release(pName);
                    pName = OBJ_NIL;
                    eRc = W32Str_Remove(this, i-2, len+3);
                    if (ERESULT_FAILED(eRc)) {
                        return ERESULT_OUT_OF_MEMORY;
                    }
                    eRc = W32Str_InsertA(this, i-2, pEnvVar);
                    if (ERESULT_FAILED(eRc)) {
                        return ERESULT_OUT_OF_MEMORY;
                    }
                    pEnvVar = NULL;
                    fMore = true;
                }
                // Not certain that we need this.
                else if (chr == '$') {
                    eRc = W32Str_Remove(this, i, 1);
                    ++i;
                    fMore = true;
                    continue;
                }
                else {
                    ++i;
                    fMore = true;
                    continue;
                }
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
        
        
        
    //---------------------------------------------------------------
    //                      F i n d  N e x t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_FindNextA(
        W32STR_DATA     *this,
        const
        char            *pStrA,             // UTF-8 String
        uint32_t        *pIndex
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        uint32_t        lenSrchStr;
        W32CHR_T        *pChr;
        W32CHR_T        chr;
        int             iRc;

        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pStrA) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        iRc = utf8_Utf8ToW32(pStrA, &chr);
        if (iRc <= 0) {
            return ERESULT_INVALID_DATA;
        }
        lenSrchStr = utf8_StrLenA(pStrA);
        if (lenSrchStr == 0) {
            return ERESULT_INVALID_DATA;
        }
        lenStr = W32Str_getLength(this);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)this, index);
        for ( i=index; i<=(lenStr - lenSrchStr + 1); ++i,++pChr ) {
            if (*pChr == chr) {
                if (0 == str_CompareNW32A(pChr, pStrA, lenSrchStr)) {
                    *pIndex = i;
                    return ERESULT_SUCCESS;
                }
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
            
            
    ERESULT         W32Str_FindNextW32(
        W32STR_DATA     *this,
        const
        W32CHR_T        *pStrW32,
        uint32_t        *pIndex
    )
    {
        uint32_t        i;
        uint32_t        iMax;
        uint32_t        index;
        uint32_t        lenStr;
        uint32_t        lenSrchStr;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pStrW32) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = W32Str_getLength(this);
        lenSrchStr = utf8_StrLenW32(pStrW32);
        if (lenSrchStr == 0) {
            return ERESULT_INVALID_DATA;
        }

        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)this, index);
        iMax = lenStr - lenSrchStr + 1;
        for ( i=index; i<=iMax; ++i,++pChr ) {
            if (*pChr == *pStrW32) {
                if (0 == str_CompareNW32(pChr, pStrW32, lenSrchStr)) {
                    *pIndex = i;
                    return ERESULT_SUCCESS;
                }
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
        
        
        
    //---------------------------------------------------------------
    //                       G e t  C h a r
    //---------------------------------------------------------------
    
    W32CHR_T        W32Str_GetCharW32(
        W32STR_DATA		*cbp,
        uint32_t        offset
    )
    {
        uint32_t        lenStr;
        W32CHR_T        chr = -1;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return 0;
        }
#endif
        lenStr = W32Str_getLength(cbp);

        if( (0 == offset) || (offset > lenStr) ) {
            return EOF;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)cbp, offset);
        if (pChr) {
            chr = *pChr;
        }
        
        // Return to caller.
        return chr;
    }
    
    
    
    //---------------------------------------------------------------
    //                          H a s h
    //---------------------------------------------------------------
    
    uint32_t        W32Str_Hash(
        W32STR_DATA       *this
    )
    {
        uint32_t        hash = 0;
        W32CHR_T        *pStr = NULL;
        
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
        }
#endif
        
        pStr = array_Ptr((ARRAY_DATA *)this, 1);
        if (pStr) {
            hash = str_HashW32(pStr, NULL);
        }
        
        return hash;
    }
    
    
    //---------------------------------------------------------------
    //                      I n d e x  U n t i l
    //---------------------------------------------------------------
    
    ERESULT         W32Str_IndexUntil(
        W32STR_DATA		*this,
        const
        W32CHR_T        *pSetStr,
        uint32_t        *pIndex
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pSetStr) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)this, index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (W32Str_ChrInStr(*pChr, pSetStr)) {
                *pIndex = i;
                return ERESULT_SUCCESS;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                          I n i t
    //---------------------------------------------------------------

    W32STR_DATA *     W32Str_Init(
        W32STR_DATA       *this
    )
    {
        uint16_t        cbSize;
        W32CHR_T        eod = 0;
        ERESULT         eRc;
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        cbSize = obj_getSize(this);
        this = (W32STR_DATA *)array_Init((ARRAY_DATA *)this);
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        obj_setSize(this, cbSize);
        this->pSuperVtbl = obj_getVtbl(this);
        obj_setVtbl(this, (void *)&W32Str_Vtbl);
        array_setElemSize((ARRAY_DATA *)this, sizeof(W32CHR_T));
        array_setZeroNew((ARRAY_DATA *)this, false);

        // Set up the End-Of-Data marker (ie '\0')
        eRc = array_AppendData((ARRAY_DATA *)this, 1, &eod);
        if (ERESULT_HAS_FAILED(eRc)) {
            DEBUG_BREAK();
            obj_Release(this);
            return OBJ_NIL;
        }
        
    #ifdef NDEBUG
    #else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            obj_Release(this);
            return OBJ_NIL;
        }
        //BREAK_NOT_BOUNDARY4(&this->thread);
        BREAK_NOT_BOUNDARY4(sizeof(W32STR_DATA));
    #endif

        return this;
    }

     

    //---------------------------------------------------------------
    //                       I n s e r t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_InsertA(
        W32STR_DATA		*cbp,
        uint32_t        offset,
        const
        char            *pStr
    )
    {
        ERESULT         eRc;
        uint32_t        i;
        uint32_t        len;
        W32CHR_T        *pInsert;
        W32CHR_T        chr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        
        if( (0 == offset) || (offset > (lenStr + 1)) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (NULL == pStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        len = (uint32_t)utf8_StrLenA(pStr);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
        
        eRc =   array_InsertSpacing(
                        (ARRAY_DATA *)cbp,
                        offset,
                        len
                );
        
        // Copy the data.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = array_Ptr((ARRAY_DATA *)cbp, offset);
            for (i=0; i<len; ++i) {
                chr = utf8_Utf8ToW32_Scan(&pStr);
                *pInsert++ = chr;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    ERESULT         W32Str_InsertW32(
        W32STR_DATA		*cbp,
        uint32_t        offset,
        const
        W32CHR_T        *pStr
    )
    {
        uint32_t        len;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
        if( (0 == offset) || (offset > W32Str_getLength(cbp)) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (NULL == pStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        len = W32Str_StrLen(pStr);
        
        eRc = array_InsertData((ARRAY_DATA *)cbp, offset, len, (void *)pStr);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                     I s  O n l y  A S C I I
    //---------------------------------------------------------------
    
    ERESULT         W32Str_IsOnlyASCII(
        W32STR_DATA		*cbp
    )
    {
        ERESULT         eRc = ERESULT_SUCCESS;
        W32CHR_T        *pData;
        uint32_t        lenStr;
    
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        
        pData = array_Ptr((ARRAY_DATA *)cbp, 1);
        if (pData) {
            while (*pData && lenStr--) {
                if (*pData > 0x7F) {
                    eRc = ERESULT_GENERAL_FAILURE;
                    break;
                }
                ++pData;
            }
        }
        
        // Return to caller.
        return eRc;
    }





    //---------------------------------------------------------------
    //                          L e f t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Left(
        W32STR_DATA		*cbp,
        uint32_t        len,
        W32STR_DATA       **ppOther           // [out]
    )
    {
        ERESULT         eRc;
        uint32_t        offset = 0;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        
        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (len > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        eRc = W32Str_Mid(cbp, 1, len, ppOther);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       L o w e r
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Lower(
        W32STR_DATA		*cbp
    )
    {
        W32CHR_T        *pData;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif

        lenStr = W32Str_getLength(cbp);
        pData  = array_Ptr((ARRAY_DATA *)cbp, 1);
        if (lenStr) {
            while( *pData && lenStr-- ) {
                *pData = ascii_toLowerW32(*pData);
                ++pData;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                          M i d
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Mid(
        W32STR_DATA		*cbp,
        uint32_t        offset,
        uint32_t        len,
        W32STR_DATA       **ppOther           // [out]
    )
    {
        W32STR_DATA       *pNew;
        ERESULT         eRc;
        uint32_t        lenStr;
        W32CHR_T        *pData;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);

        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        else {
            *ppOther = OBJ_NIL;
        }
        if( (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        pNew = W32Str_Alloc();
        pNew = W32Str_Init(pNew);
        if (OBJ_NIL == pNew) {
            return ERESULT_INSUFFICIENT_MEMORY;
        }
        pData  = array_Ptr((ARRAY_DATA *)cbp, offset);
        if (pData) {
            eRc = W32Str_AppendW32(pNew, len, pData);
        }
        else {
            return ERESULT_OUT_OF_RANGE;
        }
        
        // Return to caller.
        *ppOther = pNew;
        return ERESULT_SUCCESS;
    }
    

    
    //---------------------------------------------------------------
    //                     Q u e r y  I n f o
    //---------------------------------------------------------------
    
    void *          W32Str_QueryInfo(
        OBJ_ID          objId,
        uint32_t        type,
        void            *pData
    )
    {
        W32STR_DATA       *this = objId;
        const
        char            *pStr = pData;
        
        if (OBJ_NIL == this) {
            return NULL;
        }
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return NULL;
        }
#endif
        
        switch (type) {
                
            case OBJ_QUERYINFO_TYPE_INFO:
                return (void *)obj_getInfo(this);
                break;
                
            case OBJ_QUERYINFO_TYPE_METHOD:
                switch (*pStr) {
                        
                    case 'T':
                        if (str_Compare("ToDebugString", (char *)pStr) == 0) {
                            return W32Str_ToDebugString;
                        }
#ifdef XYZZY
                        if (str_Compare("ToJson", (char *)pStr) == 0) {
                            return W32Str_ToJSON;
                        }
#endif
                        break;
                        
                    default:
                        break;
                }
                break;
                
            default:
                break;
        }
        
        return this->pSuperVtbl->pQueryInfo(objId, type, pData);
    }
    
    
    
    //---------------------------------------------------------------
    //                          R e m o v e
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Remove(
        W32STR_DATA		*cbp,
        uint32_t        offset,
        uint32_t        len
    )
    {
        uint32_t        lenStr;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        if( (0 == offset) || (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }

        eRc = array_Delete((ARRAY_DATA *)cbp, offset, len);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                          R i g h t
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Right(
        W32STR_DATA		*cbp,
        uint32_t        len,
        W32STR_DATA       **ppOther           // [out]
    )
    {
        ERESULT         eRc;
        uint32_t        offset;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(cbp);
        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        offset = lenStr - len + 1;
        if( (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        eRc = W32Str_Mid(cbp, offset, len, ppOther);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       S e t C h a r
    //---------------------------------------------------------------
    
    ERESULT         W32Str_SetChar(
        W32STR_DATA		*this,
        uint32_t        offset,
        const
        char            chr
    )
    {
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(this);
        if ((0 == offset) || (offset > lenStr)) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        *((uint32_t *)array_Ptr((ARRAY_DATA *)this, offset)) = chr;
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                           S p a n
    //---------------------------------------------------------------
    
    ERESULT         W32Str_SpanW32(
        W32STR_DATA		*this,
        uint32_t        *pIndex,
        const
        W32CHR_T        *pSetStr
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        W32CHR_T        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pSetStr) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = array_Ptr((ARRAY_DATA *)this, index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (W32Str_ChrInStr(*pChr, pSetStr))
                ;
            else {
                *pIndex = i;
                return ERESULT_SUCCESS;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T o  C h r  C o n
    //---------------------------------------------------------------
    
    ASTR_DATA *     W32Str_ToChrCon(
        W32STR_DATA       *this
    )
    {
        const
        W32CHR_T        *pData;
        W32CHR_T        wchr;
        ASTR_DATA       *pWrkStr;
        char            work[16];
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        pWrkStr = AStr_New();
        if (OBJ_NIL == pWrkStr) {
            return pWrkStr;
        }
        
        pData = W32Str_getData(this);
        while ((wchr = *pData++)) {
            utf8_W32ToChrCon(wchr, work);
            AStr_AppendA(pWrkStr, work);
        }
        
        
        return pWrkStr;
    }
    
    
    
    //---------------------------------------------------------------
    //                     T o  I n t 3 2
    //---------------------------------------------------------------
    
    int32_t         W32Str_ToInt32(
        W32STR_DATA		*this
    )
    {
        int32_t         i = 0;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        i = dec_getInt32W32(W32Str_getData(this));

        // Return to caller.
        return i;
    }
    
    
    
    //---------------------------------------------------------------
    //                     T o  U t f 8  F i l e
    //---------------------------------------------------------------
    
    ERESULT         W32Str_ToUtf8File(
        W32STR_DATA		*this,
        PATH_DATA       *pPath
    )
    {
        FILE            *pFile = NULL;
        uint32_t        size;
        char            *pChr;
        char            *pBuffer;
        int             chr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( OBJ_NIL == pPath ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        pBuffer = W32Str_CStringA(this, &size);
        pChr = pBuffer;

        pFile = fopen(Path_getData(pPath), "wb");
        if (NULL == pFile) {
            return ERESULT_FILE_NOT_FOUND;
        }
        while ( size-- ) {
            chr = fputc(*pChr++,pFile);
            if (EOF == chr) {
                DEBUG_BREAK();
                return ERESULT_IO_ERROR;
            }
        }
        fclose(pFile);
        pFile = NULL;
        
        mem_Free(pBuffer);
        pBuffer = NULL;
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T o  S t r i n g
    //---------------------------------------------------------------
    
    ASTR_DATA * W32Str_ToDebugString(
        W32STR_DATA       *this,
        int             indent
    )
    {
        char            str[256];
        int             j;
        ASTR_DATA       *pStr;
        ASTR_DATA       *pWrkStr;
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        pStr = AStr_New();
        if (indent) {
            AStr_AppendCharRepeatW32(pStr, indent, ' ');
        }
        str[0] = '\0';
        j = snprintf(
                     str,
                     sizeof(str),
                     "{%p(WStr)\n",
                     this
                     );
        AStr_AppendA(pStr, str);
        
        pWrkStr = array_ToDebugString( &this->super, indent+3 );
        if (pWrkStr) {
            AStr_Append(pStr, pWrkStr);
            obj_Release(pWrkStr);
        }
        
        j = snprintf(str, sizeof(str), " %p(WStr)}\n", this);
        AStr_AppendA(pStr, str);
        
        return pStr;
    }
    

    
    //---------------------------------------------------------------
    //                          T r i m
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Trim(
        W32STR_DATA		*this
    )
    {
        ERESULT         eRc;
        uint32_t        i;
        uint32_t        j;
        uint32_t        lenStr;
        W32CHR_T        *pData;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(this);
        if ( 0 == lenStr ) {
            return ERESULT_SUCCESS;
        }

        // Remove leading characters.
        pData = (W32CHR_T *)W32Str_getData(this);
        j = 0;
        for (i=0; i<lenStr; ++i) {
            if (!ascii_isWhiteSpaceW32(*pData))
                break;
            ++j;
            ++pData;
        }
        if (j) {
            eRc = W32Str_Remove(this, 1, j);
        }
        
        lenStr = W32Str_getLength(this);
        if ( 0 == lenStr ) {
            return ERESULT_SUCCESS;
        }
        
        // Remove trailing characters.
        pData = (W32CHR_T *)W32Str_getData(this);
        j = 0;
        for (i=lenStr; i; --i) {
            if (!ascii_isWhiteSpaceW32(*(pData+i-1)))
                break;
            ++j;
        }
        if (j) {
            eRc = W32Str_Truncate(this, (lenStr - j));
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T r u n c a t e
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Truncate(
        W32STR_DATA		*this,
        uint32_t        len
    )
    {
        uint32_t        lenStr;
        W32CHR_T        data = 0;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(this);
        if (len > lenStr) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        // Insert new EOD char and adjust size.
        eRc = array_Put((ARRAY_DATA *)this, (len + 1), 1, &data);
        BREAK_FAILED(eRc);
        array_setSize((ARRAY_DATA *)this, (len + 1));
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       U p p e r
    //---------------------------------------------------------------
    
    ERESULT         W32Str_Upper(
        W32STR_DATA		*this
    )
    {
        W32CHR_T        *pData;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !W32Str_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = W32Str_getLength(this);
        
        if (lenStr) {
            pData = array_Ptr((ARRAY_DATA *)this, 1);
            while( *pData && lenStr-- ) {
                *pData = ascii_toUpperW32(*pData);
                ++pData;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                      V a l i d a t e
    //---------------------------------------------------------------

    #ifdef NDEBUG
    #else
    bool            W32Str_Validate(
        W32STR_DATA    *cbp
    )
    {
        if( cbp ) {
            if ( obj_IsKindOf(cbp, OBJ_IDENT_W32STR) )
                ;
            else
                return false;
        }
        else
            return false;
        if( !(obj_getSize(cbp) >= sizeof(W32STR_DATA)) )
            return false;

        // Return to caller.
        return true;
    }
    #endif


    
    
    
#ifdef	__cplusplus
}
#endif


