// vi:nu:et:sts=4 ts=4 sw=4
/*
 * File:   bstr.c
 *	Generated by 06/08/2015 18:39:43
 *
 * Created on December 30, 2014
 *
 *
 * NOTE --
 *  The underlying structure, pwr2Array, has no knowledge of the extra
 *  NUL-terminator on the string. So, it must be accounted for in these
 *  routines. Since pwr2Array is a simple array, it might be that you
 *  allocate strlen+1 for new data.
 *
 */

 
/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




//*****************************************************************
//* * * * * * * * * * * *  Data Definitions   * * * * * * * * * * *
//*****************************************************************

/* Header File Inclusion */
#include        "WStr_internal.h"
#include        "ascii.h"
#include        "str.h"
#include        "dec.h"
#include        "hex.h"
#include        "utf8.h"
#include        <stdio.h>
#include        <time.h>



#ifdef	__cplusplus
extern "C" {
#endif

    
    
    static
    const
    int32_t         whiteSpaceW[12] = {
                            ' ',
                            '\f',
                            '\n',
                            '\r',
                            '\t',
                            0x0085,     // Next New Line (Paragraph break)
                            0x00A0,     // no-break space
                            0x200B,     // zero width space
                            0x2060,     // word joiner
                            0x3000,     // ideographic space
                            0xFEFF,     // zero width no-break space
                            0
    };

    
    /*
     
     size_t    strcspn(const char *str1, const char *str2)
     
     Calculates the length of the initial segment of str1 which 
     consists entirely of characters not in str2.

     
     char *    strpbrk(const char *str1, const char *str2)
     
     Finds the first character in the string str1 that 
     matches any character specified in str2.

     
     size_t    strspn(const char *str1, const char *str2)
     
     Calculates the length of the initial segment of str1 
     which consists entirely of characters in str2.
     
     

     */


 
    /****************************************************************
    * * * * * * * * * * *  Internal Subroutines   * * * * * * * * * *
    ****************************************************************/

#ifdef XYZZY
    typedef struct RE {
        int     type;   /* CHAR, STAR, etc. */
        char    ch;     /* the character itself */
        char    *ccl;   /* for [...] instead */
        int     nccl;   /* true if class is negated [^...] */
    } RE;
    
    /* match: search for regexp anywhere in text */
    int         match(
                      char        *regexp,
                      char        *text
                      )
    {
        if (regexp[0] == '^')
            return matchhere(regexp+1, text);
        do {    /* must look even if string is empty */
            if (matchhere(regexp, text))
                return 1;
        } while (*text++ != '\0');
        return 0;
    }
    
    
    /* matchhere: search for regexp at beginning of text */
    int         matchhere(
                          char        *regexp,
                          char        *text
                          )
    {
        if (regexp[0] == '\0')
            return 1;
        if (regexp[1] == '*')
            return matchstar(regexp[0], regexp+2, text);
        if ((regexp[0] == '$') && (regexp[1] == '\0'))
            return (*text == '\0');
        if ((*text != '\0') && ((regexp[0] == '.') || (regexp[0] == *text)))
            return matchhere(regexp+1, text+1);
        return 0;
    }
    
    
    /* matchstar: search for c*regexp at beginning of text */
    int         matchstar(
                          int         c,
                          char        *regexp,
                          char        *text
                          )
    {
        do {    /* a * matches zero or more instances */
            if (matchhere(regexp, text))
                return 1;
        } while (*text != '\0' && (*text++ == c || c == '.'));
        return 0;
    }
#endif
    
    
    
    
    
    

    /****************************************************************
    * * * * * * * * * * *  External Subroutines   * * * * * * * * * *
    ****************************************************************/


    //===============================================================
    //                      *** Class Methods ***
    //===============================================================

    WSTR_DATA *     WStr_Alloc(
    )
    {
        WSTR_DATA       *cbp;
        uint32_t        cbSize = sizeof(WSTR_DATA);
        
        // Do initialization.
        
        cbp = obj_Alloc( cbSize );
        
        // Return to caller.
        return( cbp );
    }



    // Return offset of chr in string (relative to 1)
    // Returns 0 if not found.
    uint32_t        WStr_ChrInStr(
        int32_t         chr,
        const
        int32_t         *pStr
    )
    {
        uint32_t        index = 1;
        
        while (*pStr) {
            if (*pStr == chr) {
                return index;
            }
            ++pStr;
            ++index;
        }
        
        return 0;
    }
    
    
    
    ERESULT         WStr_Cmp(
        const
        int32_t         *pStr1,
        const
        int32_t         *pStr2
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        int             i;
        
        for( ;; ) {
            if( *pStr1 )
                ;
            else {
                if( *pStr2 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                break;
            }
            if( *pStr2 )
                ;
            else {
                if( *pStr1 )
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            i = *pStr1 - *pStr2;
            if( i ) {
                if( i < 0 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                else
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            ++pStr1;
            ++pStr2;
        }
        
        
        // Return to caller.
        return eRc;
    }
    
    
    
    bool            WStr_IsWhiteSpaceW(
        int32_t         chr
    )
    {
        bool            fRc = false;
        uint32_t        j;
        
        j = WStr_ChrInStr(chr, whiteSpaceW);
        if (j) {
            fRc = true;
        }
        
        // Return to caller.
        return fRc;
    }
    
    
    
    uint32_t        WStr_StrLen(
        const
        int32_t         *pData
    )
    {
        uint32_t        len = 0;
        
        while (*pData++) {
            ++len;
        }
        
        return len;
    }
    
    
    
    WSTR_DATA *     WStr_New(
    )
    {
        WSTR_DATA       *cbp;
        
        cbp = WStr_Alloc( );
        cbp = WStr_Init(cbp);
        
        // Return to caller.
        return( cbp );
    }
    
    
    
    WSTR_DATA *     WStr_NewA(
        const
        char            *pStr
    )
    {
        WSTR_DATA       *cbp;
        ERESULT         eRc;
        
        // Do initialization.
        if (NULL == pStr) {
            return OBJ_NIL;
        }
        
        cbp = WStr_Alloc( );
        cbp = WStr_Init(cbp);
        if (cbp) {
            eRc = WStr_AppendA(cbp, pStr);
            if (ERESULT_HAS_FAILED(eRc)) {
                obj_Release(cbp);
                cbp = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return( cbp );
    }
    
    
    
    WSTR_DATA *     WStr_NewW(
        uint32_t        len,
        const
        int32_t         *pStr
    )
    {
        WSTR_DATA       *cbp;
        ERESULT         eRc;
        
        // Do initialization.
        if (NULL == pStr) {
            return OBJ_NIL;
        }
        
        cbp = WStr_Alloc( );
        cbp = WStr_Init(cbp);
        if (cbp) {
            eRc = WStr_AppendW(cbp, len, pStr);
            if (ERESULT_HAS_FAILED(eRc)) {
                obj_Release(cbp);
                cbp = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return( cbp );
    }
    
    
    
    WSTR_DATA *     WStr_NewFromEnv(
        const
        char            *pStr
    )
    {
        WSTR_DATA       *cbp =  OBJ_NIL;
        char            *pData;
        size_t          len;
        
        // Do initialization.
        if (NULL == pStr) {
            return cbp;
        }
        
        pData = getenv(pStr);
        if (NULL == pData)
            ;
        else {
            len = strlen(pData);
            if (len) {
                cbp = WStr_NewA(pData);
            }
        }
        
        // Return to caller.
        return( cbp );
    }
    
    
    
    WSTR_DATA *     WStr_NewFromUtf8File(
        PATH_DATA       *pPath
    )
    {
        WSTR_DATA       *this =  OBJ_NIL;
        ERESULT         eRc;
        
        // Do initialization.
        if (NULL == pPath) {
            return this;
        }
        
        this = WStr_New( );
        if (this) {
            eRc = WStr_AppendUtf8File(this, pPath);
            if (ERESULT_FAILED(eRc)) {
                obj_Release(this);
                this = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return this;
    }
    
    
    
    WSTR_DATA *     WStr_NewFromTimeNow(
    )
    {
        WSTR_DATA       *cbp =  OBJ_NIL;
        time_t			startTime;
        char            timeStr[20];
        
        
        // Do initialization.
        startTime = time(NULL);
        strftime( timeStr, 20, "%Y-%m-%d %H:%M:%S", localtime(&startTime) );
        
        cbp = WStr_NewA(timeStr);
        
        // Return to caller.
        return( cbp );
    }
    
    
    
    const
    int32_t *       WStr_WhiteSpaceW(
    )
    {
        return whiteSpaceW;
    }
    
    
    

    

    //===============================================================
    //                      P r o p e r t i e s
    //===============================================================

    const
    int32_t *       WStr_getData(
        WSTR_DATA       *cbp
    )
    {
        int32_t         *pData;

        // Validate the input parameters.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
        }
#endif

        pData = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, 1);
        
        return pData;
    }


    uint32_t        WStr_getLength(
        WSTR_DATA       *cbp
    )
    {
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
        }
#endif
        return pwr2Array_getSize((PWR2ARRAY_DATA *)cbp) - 1;
    }




    

    //===============================================================
    //                          M e t h o d s
    //===============================================================


    //---------------------------------------------------------------
    //                       A p p e n d
    //---------------------------------------------------------------
    
    ERESULT         WStr_Append(
        WSTR_DATA		*this,
        WSTR_DATA       *pOther
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif

        if (pwr2Array_getSize((PWR2ARRAY_DATA *)pOther) > 1) {
            eRc =   pwr2Array_InsertData(
                                (PWR2ARRAY_DATA *)this,
                                pwr2Array_getSize((PWR2ARRAY_DATA *)this),
                                pwr2Array_getSize((PWR2ARRAY_DATA *)pOther)-1,
                                pwr2Array_getData((PWR2ARRAY_DATA *)pOther)
                    );
            if (ERESULT_IS_SUCCESSFUL(eRc)) {
                pwr2Array_AdjustSize( (PWR2ARRAY_DATA *)this, -1 );
            }
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    ERESULT         WStr_AppendA(
        WSTR_DATA		*cbp,
        const
        char            *pStr
    )
    {
        ERESULT         eRc;
        int32_t         chr;
        uint32_t        i;
        uint32_t        len;
        uint32_t        index;
        int32_t         *pInsert;
        
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        
        len = (uint32_t)utf8_StrLenA(pStr);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
       
        index = pwr2Array_getSize((PWR2ARRAY_DATA *)cbp);
        eRc =   pwr2Array_InsertSpacing(
                    (PWR2ARRAY_DATA *)cbp,
                    index,
                    len
                );
        
        // Copy the data.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, index);
            for (i=0; i<len; ++i) {
                chr = utf8_Utf8ToWC_Scan(&pStr);
                *pInsert++ = chr;
            }
            *pInsert = '\0';
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    ERESULT         WStr_AppendStrA(
        WSTR_DATA		*this,
        ASTR_DATA       *pStr
    )
    {
        ERESULT         eRc;
        int32_t         chr;
        uint32_t        i;
        uint32_t        len;
        uint32_t        index;
        int32_t         *pInsert;
        const
        char            *pText;
        
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        
        len = AStr_getLength(pStr);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
        pText = AStr_getData(pStr);
        
        index = pwr2Array_getSize((PWR2ARRAY_DATA *)this);
        eRc =   pwr2Array_InsertSpacing(
                                        (PWR2ARRAY_DATA *)this,
                                        index,
                                        len
                                        );
        
        // Copy the data.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = pwr2Array_Ptr((PWR2ARRAY_DATA *)this, index);
            for (i=0; i<len; ++i) {
                chr = AStr_CharGetW(pStr,(i+1));
                *pInsert++ = chr;
            }
            *pInsert = '\0';
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    ERESULT         WStr_AppendW(
        WSTR_DATA		*cbp,
        uint32_t        len,
        const
        int32_t         *pStr
    )
    {
        ERESULT         eRc = ERESULT_DATA_MISSING;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        if (0 == len) {
            len = WStr_StrLen(pStr);
        }
        if (len) {
            eRc =   pwr2Array_InsertData(
                            (PWR2ARRAY_DATA *)cbp,
                            pwr2Array_getSize((PWR2ARRAY_DATA *)cbp),
                            len,
                            (void *)pStr
                    );
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       A p p e n d  C h a r
    //---------------------------------------------------------------
    
    ERESULT         WStr_AppendCharW(
        WSTR_DATA		*cbp,
        uint32_t        len,
        const
        int32_t         chr
    )
    {
        int32_t         *pData;
        uint32_t        offset;
        uint32_t        i;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
        if (0 == len) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        offset = pwr2Array_getSize((PWR2ARRAY_DATA *)cbp);
        eRc =   pwr2Array_InsertSpacing(
                        (PWR2ARRAY_DATA *)cbp,
                        offset,
                        len
                );
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pData = pwr2Array_Ptr( (PWR2ARRAY_DATA *)cbp, offset);
            for (i=0; i<len; ++i) {
                *pData++ = chr;
            };
            //*pData = '\0';
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                    A p p e n d  F i l e
    //---------------------------------------------------------------
    
    ERESULT         WStr_AppendUtf8File(
        WSTR_DATA		*this,
        PATH_DATA       *pPath
    )
    {
        ERESULT         eRc = ERESULT_GENERAL_FAILURE;
        wint_t          chr;
        FILE            *pFile;
        
        /* Do Initialization.
         */
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( OBJ_NIL == pPath ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        pFile = fopen(path_getData(pPath), "r");
        if (NULL == pFile) {
            return ERESULT_FILE_NOT_FOUND;
        }
        while ( (chr = fgetwc(pFile)) != EOF ) {
            eRc = WStr_AppendCharW(this, 1, chr);
            if (ERESULT_FAILED(eRc)) {
                DEBUG_BREAK();
                return eRc;
            }
        }
        fclose(pFile);
        pFile = NULL;
        
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                    A p p e n d  P r i n t
    //---------------------------------------------------------------
    
    ERESULT         WStr_AppendPrint(
        WSTR_DATA		*this,
        const
        char            *pFormat,
        ...
    )
    {
        ERESULT         eRc;
        int             size;
        va_list         arg_ptr;
        char            *pStr = NULL;
        
        /* Do Initialization.
         */
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        va_start( arg_ptr, pFormat );
        size = vsnprintf( NULL, 0, pFormat, arg_ptr );
        va_end( arg_ptr );
        ++size;
        pStr = (char *)mem_Malloc( size );
        if( pStr == NULL ) {
            return ERESULT_INSUFFICIENT_MEMORY;
        }
        va_start( arg_ptr, pFormat );
        size = vsnprintf( pStr, size, pFormat, arg_ptr );
        va_end( arg_ptr );
        eRc = WStr_AppendA(this, pStr);
        mem_Free( pStr );
        pStr = NULL;
        
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       A s s i g n
    //---------------------------------------------------------------
    
    ERESULT         WStr_Assign(
        WSTR_DATA		*cbp,
        WSTR_DATA       *pOther
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( !WStr_Validate( pOther ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif

        eRc = pwr2Array_Assign((PWR2ARRAY_DATA *)cbp, (PWR2ARRAY_DATA *)pOther);
        if (ERESULT_HAS_FAILED(eRc)) {
            return eRc;
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    
    //---------------------------------------------------------------
    //               C h a r  F i n d  N e x t
    //---------------------------------------------------------------
    
    ERESULT         WStr_CharFindNextW(
        WSTR_DATA		*cbp,
        uint32_t        *pIndex,
        const
        int32_t         chr
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        int32_t         *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }

        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp,index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (chr == *pChr) {
                *pIndex = i;
                return ERESULT_SUCCESSFUL_COMPLETION;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    

    
    //---------------------------------------------------------------
    //               C h a r  F i n d  P r e v
    //---------------------------------------------------------------
    
    ERESULT         WStr_CharFindPrevW(
        WSTR_DATA		*cbp,
        uint32_t        *pIndex,
        const
        int32_t         chr
    )
    {
        uint32_t        i;
        uint32_t        index;
        int32_t         *pChr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        index = *pIndex;
        if (0 == index) {
            index = lenStr;
        }
        if (index > lenStr) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, index);
        for ( i=index; i; --i,--pChr ) {
            if (chr == *pChr) {
                *pIndex = i;
                return ERESULT_SUCCESSFUL_COMPLETION;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C h a r  G e t
    //---------------------------------------------------------------
    
    int32_t         WStr_CharGetW(
        WSTR_DATA		*cbp,
        uint32_t        offset
    )
    {
        int32_t         *pSrc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return -1;
        }
#endif
        if ((0 == offset)
            || (offset > (pwr2Array_getSize((PWR2ARRAY_DATA *)cbp))-1)) {
            return -1;
        }
        
        pSrc = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset);
        
        // Return to caller.
        return *pSrc;
    }
    
    
    
    //---------------------------------------------------------------
    //               C h a r  R e p l a c e  A l l
    //---------------------------------------------------------------
    
    ERESULT         WStr_CharReplaceAllW(
        WSTR_DATA		*cbp,
        const
        int32_t         chrSrch,
        const
        int32_t         chrRepl
    )
    {
        uint32_t        i;
        int32_t         *pChr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, 1);
        for ( i=0; i<lenStr; ++i,++pChr ) {
            if (*pChr == chrSrch) {
                *pChr = chrRepl;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C h a r  P u t
    //---------------------------------------------------------------
    
    ERESULT         WStr_CharPutW(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        const
        int32_t         chr
    )
    {
        uint32_t        lenStr;
        int32_t         *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return false;
        }
#endif
        lenStr = WStr_getLength(cbp);

        if ((0 == offset) || (offset > pwr2Array_getSize((PWR2ARRAY_DATA *)cbp))) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset);
        *pChr = chr;
        
        // Return to caller.
        return true;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C l e a n  D i r
    //---------------------------------------------------------------
    
    ERESULT         WStr_CleanDir(
        WSTR_DATA		*cbp
    )
    {
        //uint32_t        i;
        //uint32_t        *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return false;
        }
#endif
        if (0 == pwr2Array_getSize((PWR2ARRAY_DATA *)cbp)) {
            return ERESULT_SUCCESSFUL_COMPLETION;
        }
        
#ifdef XYZZY        //TODO: Fix this!
        for (i=0,pChr=cbp->pData; i<pwr2Array_getSize((PWR2ARRAY_DATA *)cbp); ++i,++pChr) {
            if ((cbp->length - i) >= 2) {
                if( (*pChr == '/') && (*(pChr+1) == '/') ) {
                    memmove(pChr, pChr+1, (cbp->length - i - 1));
                    --cbp->length;
                    continue;
                }
            }
            if ((cbp->length - i) >= 3) {
                if( (*pChr == '/') && (*(pChr+1) == '.') && (*(pChr+2) == '/') ) {
                    memmove(pChr, pChr+2, (cbp->length - i - 2));
                    --cbp->length;
                    --cbp->length;
                    continue;
                }
            }
        }
        
        if( (cbp->length >= 3)
            && (cbp->pData[cbp->length-3] == '/')
            && (cbp->pData[cbp->length-2] == '.')
            && (cbp->pData[cbp->length-1] == '/')
        ) {
            memmove(pChr, pChr+2, (cbp->length - i - 2));
            --cbp->length;
            --cbp->length;
        }
        
        while ( (cbp->pData[cbp->length-1] == '/') && (cbp->length > 1) ) {
            --cbp->length;
        }
        cbp->pData[cbp->length] = '\0';
#endif
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C o m p a r e
    //---------------------------------------------------------------
    
    ERESULT         WStr_Compare(
        WSTR_DATA		*cbp,
        WSTR_DATA       *pOther
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( !WStr_Validate( pOther ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        if( OBJ_NIL == pOther ) {
            DEBUG_BREAK();
            return ERESULT_SUCCESS_GREATER_THAN;
        }

        eRc = WStr_CompareW(cbp, pwr2Array_Ptr((PWR2ARRAY_DATA *)pOther,1));
        
        // Return to caller.
        return eRc;
    }
    
    
    ERESULT         WStr_CompareA(
        WSTR_DATA		*cbp,
        const
        char            *pString
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        uint32_t        str1len;
        const
        int32_t         *pStr1;
        uint32_t        str2len;
        uint32_t        chr2;
        int             i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        str1len = WStr_getLength(cbp);
        pStr1 = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp,1);
        if (NULL == pString) {
            str2len = 0;
        }
        else {
            str2len = (uint32_t)utf8_StrLenA(pString);
        }
        
        for( ;; ) {
            chr2 = utf8_Utf8ToWC_Scan(&pString);
            if( *pStr1 )
                ;
            else {
                if( chr2 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                break;
            }
            if( chr2 )
                ;
            else {
                if( *pStr1 )
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            i = *pStr1 - chr2;
            if( i ) {
                if( i < 0 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                else
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            ++pStr1;
        }
        
        
        // Return to caller.
        return eRc;
    }
    
    
    ERESULT         WStr_CompareW(
        WSTR_DATA		*cbp,
        const
        int32_t         *pString
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        uint32_t        str1len;
        const
        int32_t         *pStr1;
        uint32_t        str2len;
        const
        int32_t         *pStr2;
        int             i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        str1len = WStr_getLength(cbp);
        pStr1 = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp,1);
        if (NULL == pString) {
            str2len = 0;
            pStr2 = NULL;
        }
        else {
            str2len = (uint32_t)WStr_StrLen(pString);
            pStr2 = pString;
        }
        
        if ((0 == str1len) && (0 == str2len)) {
            return ERESULT_SUCCESSFUL_COMPLETION;
        }
        if ((0 == str1len) && (0 < str2len)) {
            return ERESULT_SUCCESS_LESS_THAN;
        }
        if ((0 < str1len) && (0 == str2len)) {
            return ERESULT_SUCCESS_GREATER_THAN;
        }
        
        for( ;; ) {
            if( *pStr1 )
                ;
            else {
                if( *pStr2 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                break;
            }
            if( *pStr2 )
                ;
            else {
                if( *pStr1 )
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            i = *pStr1 - *pStr2;
            if( i ) {
                if( i < 0 )
                    eRc = ERESULT_SUCCESS_LESS_THAN;
                else
                    eRc = ERESULT_SUCCESS_GREATER_THAN;
                break;
            }
            ++pStr1;
            ++pStr2;
        }
        
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                          C o p y
    //---------------------------------------------------------------
    
    WSTR_DATA *     WStr_Copy(
        WSTR_DATA		*cbp
    )
    {
        WSTR_DATA       *pOther;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
#endif
        
        pOther = WStr_New();
        if (pOther) {
            eRc = WStr_Assign(cbp, pOther);
            if (ERESULT_HAS_FAILED(eRc)) {
                obj_Release(pOther);
                pOther = OBJ_NIL;
            }
        }
        
        // Return to caller.
        return pOther;
    }
    
    
    
    //---------------------------------------------------------------
    //                       C S t r i n g A
    //---------------------------------------------------------------
    
    char *          WStr_CStringA(
        WSTR_DATA		*this,
        uint32_t        *pLen       // Optional returned string length
                                    // less terminating NUL
    )
    {
        char            *pszStr;
        uint32_t        lenStr;
        uint32_t        lenA = 0;
        uint32_t        i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return NULL;
        }
#endif
        lenStr = WStr_getLength(this);
        
        lenA =  utf8_WCToUtf8Str(
                            lenStr,
                            pwr2Array_Ptr((PWR2ARRAY_DATA *)this, 1),
                            0,
                            NULL
                );
        pszStr = (char *)mem_Malloc(lenA);
        if (pszStr) {
            i =     utf8_WCToUtf8Str(
                                     lenStr,
                                     pwr2Array_Ptr((PWR2ARRAY_DATA *)this, 1),
                                     lenA,
                                     pszStr
                                     );
            if (i<lenA) {
            }
            else {
                mem_Free(pszStr);
                return NULL;
            }
        }
        
        // Return to caller.
        if (pLen) {
            *pLen = lenA - 1;
        }
        return pszStr;
    }
    
    
    
    //---------------------------------------------------------------
    //                        D e a l l o c
    //---------------------------------------------------------------

    void            WStr_Dealloc(
        OBJ_ID          objId
    )
    {
        WSTR_DATA       *cbp = objId;

        // Do initialization.
        if (NULL == cbp) {
            return;
        }        
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return;
        }
#endif

        pwr2Array_Dealloc( cbp );
        cbp = NULL;

        // Return to caller.
    }



    //---------------------------------------------------------------
    //                     E s c a p e  F o r  C
    //---------------------------------------------------------------
    
    ERESULT         WStr_EscapeForC(
        WSTR_DATA		*this
    )
    {
        ERESULT         eRc = ERESULT_SUCCESS;
        int32_t         *pData;
        uint32_t        lenStr;
        uint32_t        i;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(this);
        
        // The order matters in how we do these replacements.
       
        for (i=1; i<=WStr_getLength(this); ++i) {
            pData = pwr2Array_Ptr((PWR2ARRAY_DATA *)this, i);
            if (pData) {
                if (*pData == '\\') {
                    pwr2Array_InsertData((PWR2ARRAY_DATA *)this, i, 1, L"\\");
                    i += 1;
                }
            }
        }
        
        for (i=1; i<=WStr_getLength(this); ++i) {
            pData = pwr2Array_Ptr((PWR2ARRAY_DATA *)this, i);
            if (pData) {
                if (*pData == '"') {
                    pwr2Array_InsertData((PWR2ARRAY_DATA *)this, i, 1, L"\\");
                    i += 1;
                }
                else if (*pData == '\n') {
                    *pData = 'n';
                    pwr2Array_InsertData((PWR2ARRAY_DATA *)this, i, 1, L"\\");
                    i += 1;
                }
                else if (*pData == '\r') {
                    *pData = 'r';
                    pwr2Array_InsertData((PWR2ARRAY_DATA *)this, i, 1, L"\\");
                    i += 1;
                }
                else if (*pData == '\t') {
                    *pData = 't';
                    pwr2Array_InsertData((PWR2ARRAY_DATA *)this, i, 1, L"\\");
                    i += 1;
                }
            }
        }
        
        // Return to caller.
        return eRc;
    }
    
    
    
    
    
    //---------------------------------------------------------------
    //                       G e t  C h a r
    //---------------------------------------------------------------
    
    int32_t         WStr_GetCharW(
        WSTR_DATA		*cbp,
        uint32_t        offset
    )
    {
        uint32_t        lenStr;
        int32_t         chr = -1;
        int32_t         *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return 0;
        }
#endif
        lenStr = WStr_getLength(cbp);

        if( (0 == offset) || (offset > lenStr) ) {
            return EOF;
        }
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset);
        if (pChr) {
            chr = *pChr;
        }
        
        // Return to caller.
        return chr;
    }
    
    
    
    //---------------------------------------------------------------
    //                          H a s h
    //---------------------------------------------------------------
    
    uint32_t        WStr_Hash(
        WSTR_DATA       *cbp
    )
    {
        uint32_t        hash = 0;
        int32_t         *pStr = NULL;
        
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
        }
#endif
        
        pStr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, 1);
        if (pStr) {
            hash = str_HashW( pStr, NULL );
        }
        
        return hash;
    }
    
    
    //---------------------------------------------------------------
    //                      I n d e x  U n t i l
    //---------------------------------------------------------------
    
    ERESULT         WStr_IndexUntil(
        WSTR_DATA		*cbp,
        const
        int32_t         *pSetStr,
        uint32_t        *pIndex
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        int32_t         *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pSetStr) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp,index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (WStr_ChrInStr(*pChr,pSetStr)) {
                *pIndex = i;
                return ERESULT_SUCCESSFUL_COMPLETION;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                          I n i t
    //---------------------------------------------------------------

    WSTR_DATA *     WStr_Init(
        WSTR_DATA       *cbp
    )
    {
        uint16_t        cbSize;
        int32_t         eod = 0;
        ERESULT         eRc;
        
        if (OBJ_NIL == cbp) {
            return OBJ_NIL;
        }
        
        cbSize = obj_getSize(cbp);
        cbp = (WSTR_DATA *)pwr2Array_Init((PWR2ARRAY_DATA *)cbp, 2);
        if (OBJ_NIL == cbp) {
            return OBJ_NIL;
        }
        obj_setSize(cbp, cbSize);
        obj_setIdent((OBJ_ID)cbp, OBJ_IDENT_WSTR);
        obj_setVtbl(cbp, (void *)&WStr_Vtbl);
        pwr2Array_setDontZero((PWR2ARRAY_DATA *)cbp, true);

        // Set up the End-Of-Data marker (ie '\0')
        eRc = pwr2Array_AppendData((PWR2ARRAY_DATA *)cbp, 1, &eod);
        if (ERESULT_HAS_FAILED(eRc)) {
            DEBUG_BREAK();
            obj_Release(cbp);
            return OBJ_NIL;
        }
        
    #ifdef NDEBUG
    #else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            obj_Release(cbp);
            return OBJ_NIL;
        }
        //BREAK_NOT_BOUNDARY4(&cbp->thread);
    #endif

        return cbp;
    }

     

    //---------------------------------------------------------------
    //                       I n s e r t
    //---------------------------------------------------------------
    
    ERESULT         WStr_InsertA(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        const
        char            *pStr
    )
    {
        ERESULT         eRc;
        uint32_t        i;
        uint32_t        len;
        int32_t         *pInsert;
        int32_t         chr;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        if( (0 == offset) || (offset > (lenStr + 1)) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (NULL == pStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        len = (uint32_t)utf8_StrLenA(pStr);
        if (0 == len) {
            return ERESULT_DATA_NOT_FOUND;
        }
        
        eRc =   pwr2Array_InsertSpacing(
                        (PWR2ARRAY_DATA *)cbp,
                        offset,
                        len
                );
        
        // Copy the data.
        if (ERESULT_IS_SUCCESSFUL(eRc)) {
            pInsert = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset);
            for (i=0; i<len; ++i) {
                chr = utf8_Utf8ToWC_Scan(&pStr);
                *pInsert++ = chr;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    
    ERESULT         WStr_InsertW(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        const
        int32_t         *pStr
    )
    {
        uint32_t        len;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
        if( (0 == offset) || (offset > WStr_getLength(cbp)) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (NULL == pStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        len = WStr_StrLen(pStr);
        
        eRc = pwr2Array_InsertData((PWR2ARRAY_DATA *)cbp, offset, len, (void *)pStr);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                     I s  O n l y  A S C I I
    //---------------------------------------------------------------
    
    ERESULT         WStr_IsOnlyASCII(
        WSTR_DATA		*cbp
    )
    {
        ERESULT         eRc = ERESULT_SUCCESSFUL_COMPLETION;
        int32_t         *pData;
        uint32_t        lenStr;
    
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        pData = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, 1);
        if (pData) {
            while (*pData && lenStr--) {
                if (*pData > 0x7F) {
                    eRc = ERESULT_GENERAL_FAILURE;
                    break;
                }
                ++pData;
            }
        }
        
        // Return to caller.
        return eRc;
    }





    //---------------------------------------------------------------
    //                          L e f t
    //---------------------------------------------------------------
    
    ERESULT         WStr_Left(
        WSTR_DATA		*cbp,
        uint32_t        len,
        WSTR_DATA       **ppOther           // [out]
    )
    {
        ERESULT         eRc;
        uint32_t        offset = 0;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        if( (len > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        eRc = WStr_Mid(cbp, 1, len, ppOther);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       L o w e r
    //---------------------------------------------------------------
    
    ERESULT         WStr_Lower(
        WSTR_DATA		*cbp
    )
    {
        int32_t         *pData;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif

        lenStr = WStr_getLength(cbp);
        pData  = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, 1);
        if (lenStr) {
            while( *pData && lenStr-- ) {
                if( (*pData >= 'A') && (*pData <= 'Z') )
                    *pData = (char)(*pData + ('a' - 'A'));
                ++pData;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESSFUL_COMPLETION;
    }
    
    
    
    //---------------------------------------------------------------
    //                          M i d
    //---------------------------------------------------------------
    
    ERESULT         WStr_Mid(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        uint32_t        len,
        WSTR_DATA       **ppOther           // [out]
    )
    {
        WSTR_DATA       *pNew;
        ERESULT         eRc;
        uint32_t        lenStr;
        int32_t         *pData;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);

        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        else {
            *ppOther = OBJ_NIL;
        }
        if( (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        pNew = WStr_Alloc();
        pNew = WStr_Init(pNew);
        if (OBJ_NIL == pNew) {
            return ERESULT_INSUFFICIENT_MEMORY;
        }
        pData  = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset);
        if (pData) {
            eRc = WStr_AppendW(pNew, len, pData);
        }
        else {
            return ERESULT_OUT_OF_RANGE;
        }
        
        // Return to caller.
        *ppOther = pNew;
        return ERESULT_SUCCESS;
    }
    

    
    //---------------------------------------------------------------
    //                          R e m o v e
    //---------------------------------------------------------------
    
    ERESULT         WStr_Remove(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        uint32_t        len
    )
    {
        uint32_t        lenStr;
        ERESULT         eRc;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        if( (0 == offset) || (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }

        eRc = pwr2Array_Delete((PWR2ARRAY_DATA *)cbp, offset, len);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                          R i g h t
    //---------------------------------------------------------------
    
    ERESULT         WStr_Right(
        WSTR_DATA		*cbp,
        uint32_t        len,
        WSTR_DATA       **ppOther           // [out]
    )
    {
        ERESULT         eRc;
        uint32_t        offset;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        if (NULL == ppOther) {
            return ERESULT_INVALID_PARAMETER;
        }
        offset = lenStr - len + 1;
        if( (offset > lenStr) ) {
            return ERESULT_INVALID_PARAMETER;
        }
        if ((0 == lenStr) || ((offset + len - 1) > lenStr)) {
            return ERESULT_OUT_OF_RANGE;
        }
        
        eRc = WStr_Mid(cbp, offset, len, ppOther);
        
        // Return to caller.
        return eRc;
    }
    
    
    
    //---------------------------------------------------------------
    //                       S e t C h a r
    //---------------------------------------------------------------
    
    ERESULT         WStr_SetChar(
        WSTR_DATA		*cbp,
        uint32_t        offset,
        const
        char            chr
    )
    {
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(cbp);
        if ((0 == offset) || (offset > lenStr)) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        *((uint32_t *)pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp, offset)) = chr;
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                           S p a n
    //---------------------------------------------------------------
    
    ERESULT         WStr_SpanW(
        WSTR_DATA		*cbp,
        uint32_t        *pIndex,
        const
        int32_t         *pSetStr
    )
    {
        uint32_t        i;
        uint32_t        index;
        uint32_t        lenStr;
        int32_t         *pChr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( cbp ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if (NULL == pIndex) {
            return ERESULT_INVALID_PARAMETER;
        }
        if (NULL == pSetStr) {
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        lenStr = WStr_getLength(cbp);
        
        index = *pIndex;
        if (0 == index) {
            index = 1;
        }
        if (index > lenStr) {
            *pIndex = 0;
            return ERESULT_OUT_OF_RANGE;
        }
        
        pChr = pwr2Array_Ptr((PWR2ARRAY_DATA *)cbp,index);
        for ( i=index; i<lenStr; ++i,++pChr ) {
            if (WStr_ChrInStr(*pChr,pSetStr))
                ;
            else {
                *pIndex = i;
                return ERESULT_SUCCESS;
            }
        }
        
        // Return to caller.
        *pIndex = 0;
        return ERESULT_OUT_OF_RANGE;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T o  C h r  C o n
    //---------------------------------------------------------------
    
    ASTR_DATA *     WStr_ToChrCon(
        WSTR_DATA       *this
    )
    {
        const
        int32_t         *pData;
        int32_t         wchr;
        ASTR_DATA       *pWrkStr;
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        pWrkStr = AStr_New();
        if (OBJ_NIL == pWrkStr) {
            return pWrkStr;
        }
        
        pData = WStr_getData(this);
        while ((wchr = *pData)) {
            if (ascii_isAsciiW(wchr) && ascii_isPrintableA(wchr)) {
                AStr_AppendCharA(pWrkStr, wchr);
            }
            else if (wchr < 256) {
                switch (wchr) {
                        
                    case 9:
                        AStr_AppendA(pWrkStr, "\\t");
                        break;
                        
                    case 10:
                        AStr_AppendA(pWrkStr, "\\n");
                        break;
                        
                    case 12:
                        AStr_AppendA(pWrkStr, "\\f");
                        break;
                        
                    case 13:
                        AStr_AppendA(pWrkStr, "\\r");
                        break;
                        
                    default:
                        AStr_AppendA(pWrkStr, "\\x");
                        AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 4) & 0xF));
                        AStr_AppendCharA(pWrkStr, hex_DigitToChrA(wchr & 0xF));
                        break;
                }
            }
            else if (wchr < 65236) {
                AStr_AppendA(pWrkStr, "\\u");
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 12) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 8) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 4) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA(wchr & 0xF));
            }
            else {
                AStr_AppendA(pWrkStr, "\\U");
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 28) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 24) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 20) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 16) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 12) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 8) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA((wchr >> 4) & 0xF));
                AStr_AppendCharA(pWrkStr, hex_DigitToChrA(wchr & 0xF));
            }
            ++pData;
        }
        
        
        return pWrkStr;
    }
    
    
    
    //---------------------------------------------------------------
    //                     T o  I n t 3 2
    //---------------------------------------------------------------
    
    int32_t         WStr_ToInt32(
        WSTR_DATA		*this
    )
    {
        int32_t         i = 0;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
#endif
        
        i = dec_getInt32W(WStr_getData(this));

        // Return to caller.
        return i;
    }
    
    
    
    ASTR_DATA *     WStr_ToJSON(
        WSTR_DATA       *this
    )
    {
        ASTR_DATA       *pStr;
        ASTR_DATA       *pWrkStr;
        const
        OBJ_INFO        *pInfo;
        
#ifdef NDEBUG
#else
        if( !WStr_Validate( this ) ) {
            DEBUG_BREAK();
            return OBJ_NIL;
        }
#endif
        pInfo = obj_getInfo(this);
        pWrkStr = WStr_ToChrCon(this);
        if (pWrkStr == OBJ_NIL) {
            return OBJ_NIL;
        }
        
        pStr = AStr_New();
        if (pWrkStr == OBJ_NIL) {
            obj_Release(pWrkStr);
            return OBJ_NIL;
        }
        AStr_AppendA(pStr, "{\"objectType\":\"");
        AStr_AppendA(pStr, pInfo->pClassName);
        AStr_AppendA(pStr, "\",\"data\":\"");
        AStr_Append(pStr, pWrkStr);
        AStr_AppendA(pStr, "\"}\n");
        obj_Release(pWrkStr);
        
        return pStr;
    }
    
    
    
    //---------------------------------------------------------------
    //                     T o  U t f 8  F i l e
    //---------------------------------------------------------------
    
    ERESULT         WStr_ToUtf8File(
        WSTR_DATA		*this,
        PATH_DATA       *pPath
    )
    {
        FILE            *pFile = NULL;
        uint32_t        size;
        char            *pChr;
        char            *pBuffer;
        int             chr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_OBJECT;
        }
        if( OBJ_NIL == pPath ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_PARAMETER;
        }
#endif
        
        pBuffer = WStr_CStringA(this, &size);
        pChr = pBuffer;

        pFile = fopen(path_getData(pPath), "wb");
        if (NULL == pFile) {
            return ERESULT_FILE_NOT_FOUND;
        }
        while ( size-- ) {
            chr = fputc(*pChr++,pFile);
            if (EOF == chr) {
                DEBUG_BREAK();
                return ERESULT_IO_ERROR;
            }
        }
        fclose(pFile);
        pFile = NULL;
        
        mem_Free(pBuffer);
        pBuffer = NULL;
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T o  S t r i n g
    //---------------------------------------------------------------
    
    ASTR_DATA * WStr_ToDebugString(
        WSTR_DATA       *this,
        int             indent
    )
    {
        char            str[256];
        int             j;
        ASTR_DATA       *pStr;
        ASTR_DATA       *pWrkStr;
        
        if (OBJ_NIL == this) {
            return OBJ_NIL;
        }
        
        pStr = AStr_New();
        if (indent) {
            AStr_AppendCharRepeatW(pStr, indent, ' ');
        }
        str[0] = '\0';
        j = snprintf(
                     str,
                     sizeof(str),
                     "{%p(WStr)\n",
                     this
                     );
        AStr_AppendA(pStr, str);
        
        pWrkStr = pwr2Array_ToDebugString( &this->super, indent+3 );
        if (pWrkStr) {
            AStr_Append(pStr, pWrkStr);
            obj_Release(pWrkStr);
        }
        
        j = snprintf(str, sizeof(str), " %p(WStr)}\n", this);
        AStr_AppendA(pStr, str);
        
        return pStr;
    }
    

    
    //---------------------------------------------------------------
    //                          T r i m
    //---------------------------------------------------------------
    
    ERESULT         WStr_Trim(
        WSTR_DATA		*this
    )
    {
        ERESULT         eRc;
        uint32_t        i;
        uint32_t        j;
        uint32_t        k;
        uint32_t        lenStr;
        int32_t         *pData;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(this);
        if ( 0 == lenStr ) {
            return ERESULT_SUCCESS;
        }

        // Remove leading characters.
        pData = (int32_t *)WStr_getData(this);
        k = 0;
        for (i=1; i<=lenStr; ++i) {
            j = WStr_ChrInStr(*pData, whiteSpaceW);
            if (0 == j) {
                break;
            }
            ++k;
            ++pData;
        }
        if (k) {
            eRc = WStr_Remove(this, 1, k);
        }
        
        lenStr = WStr_getLength(this);
        if ( 0 == lenStr ) {
            return ERESULT_SUCCESSFUL_COMPLETION;
        }
        
        // Remove trailing characters.
        pData = (int32_t *)WStr_getData(this);
        k = 0;
        for (i=lenStr; i; --i) {
            j = WStr_ChrInStr(pData[i-1], whiteSpaceW);
            if (0 == j) {
                break;
            }
            ++k;
        }
        if (k) {
            eRc = WStr_Truncate(this, (lenStr - k));
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       T r u n c a t e
    //---------------------------------------------------------------
    
    ERESULT         WStr_Truncate(
        WSTR_DATA		*this,
        uint32_t        len
    )
    {
        uint32_t        lenStr;
        int32_t         *pData;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate( this ) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(this);
        if (len > lenStr) {
            return ERESULT_INVALID_PARAMETER;
        }
        
        // Insert new EOD char and adjust size.
        pData  = pwr2Array_Ptr((PWR2ARRAY_DATA *)this, (len + 1));
        if (pData) {
            *pData = '\0';
        }
        pwr2Array_setSize((PWR2ARRAY_DATA *)this, (len + 1));
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                       U p p e r
    //---------------------------------------------------------------
    
    ERESULT         WStr_Upper(
        WSTR_DATA		*this
    )
    {
        int32_t         *pData;
        uint32_t        lenStr;
        
        // Do initialization.
#ifdef NDEBUG
#else
        if( !WStr_Validate(this) ) {
            DEBUG_BREAK();
            return ERESULT_INVALID_DATA;
        }
#endif
        lenStr = WStr_getLength(this);
        
        if (lenStr) {
            pData = pwr2Array_Ptr((PWR2ARRAY_DATA *)this, 1);
            while( *pData && lenStr-- ) {
                if( (*pData >= 'a') && (*pData <= 'z') )
                    *pData = (char)(*pData - ('a' - 'A'));
                ++pData;
            }
        }
        
        // Return to caller.
        return ERESULT_SUCCESS;
    }
    
    
    
    //---------------------------------------------------------------
    //                      V a l i d a t e
    //---------------------------------------------------------------

    #ifdef NDEBUG
    #else
    bool            WStr_Validate(
        WSTR_DATA      *cbp
    )
    {
        if( cbp ) {
            if ( obj_IsKindOf(cbp, OBJ_IDENT_WSTR) )
                ;
            else
                return false;
        }
        else
            return false;
        if( !(obj_getSize(cbp) >= sizeof(WSTR_DATA)) )
            return false;

        // Return to caller.
        return true;
    }
    #endif


    
    
    
#ifdef	__cplusplus
}
#endif


